(()=>{
const R=window.R;if(!R||R.__homeUI381)return;R.__homeUI381=true;const $=s=>document.querySelector(s),C=globalThis.RADIO_APP_CONFIG||{timezone:'Europe/Istanbul'},esc=v=>R.esc?R.esc(v):String(v??''),norm=v=>R.norm?R.norm(v):String(v??'').toLocaleLowerCase('tr-TR');
const BAND_ORDER=['FM','MW','SW1','SW2','SW3','SW4','SW5','SW6','SW7','SW8','SW9','SW10'];
function ensureTab(){let t=$('#tab-home');if(!t){t=document.createElement('section');t.id='tab-home';t.className='tab-view hidden';const app=$('#appView'),log=$('#tab-log');app?.insertBefore(t,log||app.firstChild)}return t}
function ensure(){const t=ensureTab();let x=$('#v38Home');if(!x){x=document.createElement('div');x.id='v38Home';x.className='v38-home';t.appendChild(x)}return x}
function parts(){return R.clock?.parts?.()||{date:new Date().toLocaleDateString('en-CA'),hour:new Date().getHours()}}
function labelNow(){return R.clock?.format?.(new Date(),{weekday:'long',day:'numeric',month:'long',hour:'2-digit',minute:'2-digit',hourCycle:'h23'})||new Date().toLocaleString('tr-TR')}
function originName(){return R.listeningOrigin?.()?.name||C.origin?.name||'Bozköy, Torbalı, İzmir'}
function band(e){return e?.mode==='SW'?(e.band||'SW'):(e?.mode||e?.band||'')}
function unit(e){return e?.unit||((e?.mode||e?.band)==='FM'?'MHz':'kHz')}
function freq(e){return `${Number(e?.frequency||0).toLocaleString('tr-TR',{maximumFractionDigits:3})} ${unit(e)}`}
function lang(e){return String(e?.language_content||'').split(/[;/,]/)[0].trim()}
function score(e){return Math.max(1,Math.min(99,Math.round(Number(e?._score??e?._s?.score??e?.probability_score??50))))}
function quality(n){return n>=80?'Çok iyi':n>=65?'İyi':n>=50?'Orta':'Zayıf'}
function candidates(mode='ALL'){try{const a=R.radioNowCandidates?.(mode);if(Array.isArray(a))return a}catch{}try{const a=R.currentSuggestions?.()||[];return mode==='ALL'?a:a.filter(x=>x.mode===mode)}catch{return[]}}
function stationOf(x){return String(x?.station||x?.smart_station||'').trim()}
function split(v){return String(v||'').split(/[/,;]/).map(x=>x.trim()).filter(Boolean)}
function streak(){const set=new Set((R.logs||[]).map(x=>x.date).filter(Boolean));let n=0;const today=R.clock?.today?.()||new Date().toLocaleDateString('en-CA');for(let i=0;i<366;i++){const d=new Date(today+'T12:00:00Z');d.setUTCDate(d.getUTCDate()-i);const k=d.toISOString().slice(0,10);if(set.has(k))n++;else if(i===0)continue;else break}return n}
function countries(){return new Set((R.logs||[]).flatMap(x=>split(x.country)).map(norm).filter(Boolean)).size}
function readWeather(){try{const x=JSON.parse(localStorage.getItem('radio-space-weather-v41')||'null');return x&&Date.now()-Number(x.savedAt||0)<86400000?x:null}catch{return null}}
function propagationText(){const w=readWeather(),kp=Number(w?.kp),h=parts().hour,phase=h>=7&&h<19?'Gündüz':(h>=19&&h<21||h>=5&&h<7?'Gün-gece sınırı':'Gece');return `${Number.isFinite(kp)?`Kp ${kp.toFixed(1)}`:'Kp —'} · ${phase}`}
function dialPosition(e){const i=BAND_ORDER.indexOf(band(e));return i<0?50:Math.max(2,Math.min(98,i/(BAND_ORDER.length-1)*100))}
function radioConsole(selected,total){const pos=dialPosition(selected);return `<div class="v42-radio-console"><div class="v42-console-id"><span>TECSUN</span><b>R-9012</b><small>12 bantlı saha alıcısı</small></div><div class="v42-radio-dial" aria-label="R-9012 bant kadranı"><div class="v42-radio-scale">${BAND_ORDER.map(x=>`<span class="${x===band(selected)?'active':''}">${x}</span>`).join('')}</div><i class="v42-radio-needle" style="left:${pos}%"></i></div><div class="v42-console-live"><span class="v42-live-dot"></span><b>${Number(total||0).toLocaleString('tr-TR')}</b><small>uygun aday</small></div></div>`}
function weekActivity(logs){const today=R.clock?.today?.()||new Date().toLocaleDateString('en-CA'),rows=[];for(let i=6;i>=0;i--){const d=new Date(today+'T12:00:00Z');d.setUTCDate(d.getUTCDate()-i);const date=d.toISOString().slice(0,10),count=logs.filter(x=>x.date===date).length,label=new Intl.DateTimeFormat('tr-TR',{weekday:'short'}).format(d).replace('.','');rows.push({date,count,label})}const max=Math.max(1,...rows.map(x=>x.count));return `<div class="v42-week"><div class="v42-week-head"><div><small>SON 7 GÜN</small><b>Dinleme sıklığı</b></div><span>${rows.reduce((s,x)=>s+x.count,0)} kayıt</span></div><div class="v42-week-bars">${rows.map(x=>`<div class="v42-week-day" title="${esc(x.date)} · ${x.count} kayıt"><b>${x.count||''}</b><i><em style="height:${Math.max(8,Math.round(x.count/max*100))}%"></em></i><span>${esc(x.label)}</span></div>`).join('')}</div></div>`}
function primaryCard(e){if(!e)return '<div class="v42-empty-card"><b>Şu anda dinlemeye uygun bir yayın adayı yok</b><span>Yayın rehberini veya yayılım asistanını kontrol edebilirsin.</span><div><button class="btn ghost" data-route="guide">Rehberi aç</button><button class="btn ghost" data-route="propagation">Yayılımı aç</button></div></div>';const s=score(e);return `<article class="v42-primary"><div class="v42-primary-head"><span class="v42-band">${esc(band(e))}</span><span class="v42-quality q${Math.floor(s/10)}">${s} · ${quality(s)}</span></div><div class="v42-frequency">${freq(e)}</div><div class="v42-freq-ruler" aria-hidden="true"></div><h3>${esc(e.station||'Yayın adayı')}</h3><p>${esc([lang(e)||e.country,e.time_text].filter(Boolean).join(' · '))}</p><div class="v42-primary-actions"><button class="btn primary" data-listen="${esc(e.id)}">Dinlemeye başla</button><button class="btn ghost" data-route="now">Diğer yayınlar</button></div></article>`}
function render(){const root=ensure(),all=candidates('ALL'),a=all.slice(0,3),p=parts(),logs=R.logs||[],today=logs.filter(x=>x.date===p.date),last=logs[0],g=p.hour<12?'Günaydın':p.hour<18?'İyi günler':'İyi akşamlar',where=originName();root.innerHTML=`<div class="v42-home"><section class="v42-home-hero"><div class="v42-home-top"><div><span class="v42-kicker">${esc(where)} · ${esc(labelNow())}</span><h2>${g}</h2><p>Radyoyu açtığında, önce hangi yayınları denemeye değer olduğunu burada görebilirsin.</p></div><button class="v42-search-button" data-v44search aria-label="Ara"><span>⌕</span> Ara</button></div><div class="v42-home-grid">${primaryCard(a[0])}<button class="v42-prop-card" data-route="propagation"><span class="v42-prop-icon">◌</span><div><small>Yayılım</small><b>${esc(propagationText())}</b><span>Koşulları ve bant sıralamasını gör</span></div><i>›</i></button></div>${radioConsole(a[0],all.length)}</section>${a.length>1?`<section class="v42-section v42-onair-section"><div class="v42-section-head"><div><span class="v42-section-kicker">ŞİMDİ DİNLENEBİLİR</span><h3>Diğer uygun adaylar</h3><p>Tek dokunuşla dinlemeye başla.</p></div><button class="v42-link" data-route="now">Tümünü gör</button></div><div class="v42-alt-grid">${a.slice(1).map(e=>{const s=score(e);return `<button class="v42-alt" data-listen="${esc(e.id)}"><span class="v42-alt-band">${esc(band(e))}</span><div><b>${freq(e)}</b><span>${esc(e.station||'Yayın adayı')}</span><small>${esc(lang(e)||e.country||'')}</small></div><em>${s}</em></button>`}).join('')}</div></section>`:''}<section class="v42-section v42-journal-section"><div class="v42-section-head"><div><span class="v42-section-kicker">KİŞİSEL SAHA GÜNLÜĞÜ</span><h3>Dinleme geçmişin</h3><p>Kayıtların biriktikçe kişisel alım profilin güçlenir.</p></div><button class="v42-link" data-route="log">Günlüğü aç</button></div><div class="v42-dashboard"><div><b>${today.length}</b><span>bugünkü kayıt</span></div><div><b>${countries()}</b><span>ülke</span></div><div><b>${streak()}</b><span>ardışık gün</span></div></div>${weekActivity(logs)}${last?`<button class="v42-last" data-log="${last.id}"><div><small>Son kayıt</small><b>${esc(stationOf(last)||`${last.band||''} ${last.frequency||''}`)}</b><span>${esc([last.band,last.frequency!=null?Number(last.frequency).toLocaleString('tr-TR',{maximumFractionDigits:3}):'',last.language,last.signal_strength?`${last.signal_strength}/5`:null].filter(Boolean).join(' · '))}</span></div><i>›</i></button>`:'<div class="v42-empty-card"><b>Henüz kayıt yok</b><span>İlk yayını kaydettiğinde kişisel dinleme geçmişin burada oluşmaya başlayacak.</span></div>'}</section></div>`}
R.events?.on?.('store:updated',()=>{if(R.router?.current?.()==='home')render()});R.events?.on?.('user:settings',()=>{if(R.router?.current?.()==='home')render()});
R.homeUI={render,ensure};R.router?.register?.('home',{prepare:ensure,enter:render});R.features?.register?.('home-ui',{ready:true,provider:'app-home-ui'});ensure();
})();