(()=>{
const R=window.R;if(!R||R.__menuUI381)return;R.__menuUI381=true;
const $=s=>document.querySelector?.(s)||null,$$=s=>typeof document.querySelectorAll==='function'?[...document.querySelectorAll(s)]:[],esc=v=>R.esc?R.esc(v):String(v??'');
let returnFocus=null,lifecycle=0;const DIAG_OWNER_KEY='radio-diagnostics-owner-v1',syncFlights=new Map();
function css(){if(document.querySelector?.('link[data-menu-css]')||typeof document.createElement!=='function')return;const l=document.createElement('link');l.rel='stylesheet';l.href='app-menu.css';l.dataset.menuCss='1';document.head?.appendChild?.(l)}css();
function activeUserId(){return R.me?.id||null}
function menuTriggers(opened){for(const b of $$('[data-menu]')){b.setAttribute('aria-haspopup','dialog');b.setAttribute('aria-expanded',opened?'true':'false');if(opened)b.setAttribute('aria-controls','v38Sheet');else b.removeAttribute('aria-controls')}}
function removeSheet(){$('#v38Overlay')?.remove();$('#v38Sheet')?.remove();document.documentElement.classList.remove('v38-menu-open');menuTriggers(false)}
function close({restoreFocus=true}={}){lifecycle++;removeSheet();const target=returnFocus;returnFocus=null;if(restoreFocus&&target?.isConnected)target.focus?.();return true}
function bindGroups(s){const groups=[...s.querySelectorAll('.v38-menu-group')];for(const group of groups)group.addEventListener('toggle',()=>{if(!group.open)return;for(const other of groups)if(other!==group&&other.open)other.open=false})}
function revealCurrentRoute(s){const current=s.querySelector('.v38-menu-row[aria-current="page"]');if(!current)return null;const group=current.closest('.v38-menu-group');if(group)group.open=true;return current}
function sheet(title,body,{view='main',subtitle='',backAction=null,focusAction=null}={}){const old=$('#v38Sheet');if(!returnFocus&&document.activeElement instanceof HTMLElement&&(!old||!old.contains(document.activeElement)))returnFocus=document.activeElement;removeSheet();const o=document.createElement('div');o.id='v38Overlay';o.className='v38-overlay';o.onclick=()=>close();const s=document.createElement('div');s.id='v38Sheet';s.className='v38-sheet v38-menu-sheet';s.dataset.menuView=view;s.setAttribute('role','dialog');s.setAttribute('aria-modal','true');s.setAttribute('aria-labelledby','v38SheetTitle');s.innerHTML=`<div class="v38-sheethead">${backAction?`<button class="v38-menu-back" type="button" data-action="${esc(backAction)}" aria-label="Ana menüye dön">←</button>`:''}<div class="v38-menu-headcopy"><small>RADYO GÜNLÜĞÜM</small><h2 id="v38SheetTitle">${esc(title)}</h2>${subtitle?`<p>${esc(subtitle)}</p>`:''}</div><button class="v38-close" type="button" aria-label="Menüyü kapat">×</button></div>${body}`;document.body.append(o,s);document.documentElement.classList.add('v38-menu-open');menuTriggers(true);const closeButton=s.querySelector('.v38-close');closeButton.onclick=()=>close();bindGroups(s);if(view==='main')revealCurrentRoute(s);const preferred=focusAction?s.querySelector(`[data-action="${focusAction}"]`):null;(preferred||closeButton||s).focus?.();R.events?.emit?.('menu:opened',{sheet:s,title,view});return s}
function routeCurrent(action){return action?.startsWith('route:')&&R.router?.current?.()===action.slice(6)}
function row(a,b,action,{state='',pressed=null,disabled=false}={}){const current=routeCurrent(action),attrs=[`data-action="${esc(action)}"`,'type="button"'];if(current)attrs.push('aria-current="page"');if(pressed!==null)attrs.push(`aria-pressed="${pressed?'true':'false'}"`);if(disabled)attrs.push('disabled','aria-disabled="true"');return `<button class="v38-menu-row${current?' is-current':''}" ${attrs.join(' ')}><span class="v38-menu-copy"><b>${esc(a)}</b><small>${esc(b)}</small></span><span class="v38-menu-tail">${state?`<em class="v38-menu-state">${esc(state)}</em>`:''}<i aria-hidden="true">›</i></span></button>`}
function themeNight(){return document.body.classList.contains('night-mode')||document.documentElement.classList.contains('night')}
function installState(){const installed=!!R.pwaInstall?.isStandalone?.(),ready=!!R.installPrompt;return{installed,ready,state:installed?'Kurulu':ready?'Hazır':'İsteğe bağlı',desc:installed?'Uygulama modunda açık':ready?'Bu cihazda kuruluma hazır':'Ana ekrana veya uygulamalar listesine ekle'}}
function open({focusAction=null,preserveLifecycle=false}={}){if(!preserveLifecycle)lifecycle++;const night=themeNight(),install=installState();return sheet('Menü',`<button class="v42-menu-search" type="button" data-action="search"><span aria-hidden="true">⌕</span><span><b>Uygulamada ara</b><small>İstasyon, frekans, kayıt veya araç bul</small></span><i aria-hidden="true">›</i></button><div class="v38-menu-groups"><details class="v38-menu-group"><summary><span class="v38-menu-group-title"><i aria-hidden="true">◇</i>Koleksiyon</span></summary><div class="v38-menu-list">${row('Radyo hafızası','İstasyon, frekans ve ülke profilleri','route:memory')}${row('Radyo atlası','Ülke, yön ve dinleme geçmişi','route:atlas')}${row('QSL','Alım raporları ve yanıtlar','route:qsl')}${row('Başarılar','Rozetler ve koleksiyon ilerlemesi','achievements')}${row('Favoriler','Kaydettiğin yayın hedefleri','favorites')}</div></details><details class="v38-menu-group"><summary><span class="v38-menu-group-title"><i aria-hidden="true">⌁</i>Araçlar</span></summary><div class="v38-menu-list">${row('Yayılım asistanı','Gün-gece sınırı, uzay havası ve kişisel bant tahmini','route:propagation')}${row('Radyo sözlüğü','Teknik terimlerin sade Türkçe açıklamaları','radio-glossary')}${row('Yapay zekâ ile ses analizi','Ses, dil ve istasyon adayları','route:ai')}${row('Yayın rehberi','Frekanslar ve yayın saatleri','route:guide')}${row('Akıllı dinleme','Oturumlar, tanımlanamayan yayınlar ve kalibrasyon','route:smart')}${row('Ses kaydı','Radyo sesini kaydet ve yazıya dök','route:audio')}${row('Konum haritası','Konum bilgisi eklenen dinleme kayıtları','route:map')}</div></details><details class="v38-menu-group"><summary><span class="v38-menu-group-title"><i aria-hidden="true">▤</i>Geçmiş</span></summary><div class="v38-menu-list">${row('Günlük','Tüm dinleme kayıtların','route:log')}${row('Takvim','Dinleme günlerinin takvimi','route:calendar')}${row('İstatistikler','Bant, dil ve sinyal analizi','route:analysis')}</div></details><details class="v38-menu-group"><summary><span class="v38-menu-group-title"><i aria-hidden="true">⚙</i>Ayarlar</span></summary><div class="v38-menu-list">${row('Hatırlatıcılar','Yayın saatleri için bildirimler','reminders')}${row('Görünüm',night?'Gece görünümü açık':'Açık görünüm açık','theme',{state:night?'Gece':'Açık',pressed:night})}${row('Senkronizasyon','Çevrimdışı kayıtları bulutla eşitle','sync',{state:syncFlights.has(activeUserId())?'Çalışıyor':'Hazır'})}${row('Sistem durumu','Uygulama ve veri denetimleri','diagnostics')}${row('Uygulamayı kur',install.desc,'install',{state:install.state,disabled:install.installed})}</div></details></div><div class="v38-menu-footer"><button class="btn ghost" type="button" data-action="logout">Çıkış yap</button></div>`,{view:'main',subtitle:'Koleksiyon, araçlar, geçmiş ve ayarlar',focusAction})}
function ownedRows(rows,userId){return(Array.isArray(rows)?rows:[]).filter(x=>x?.user_id===userId)}
function frequencyText(x){const n=Number(x?.frequency);if(!Number.isFinite(n)||n<=0)return'';const band=String(x?.band||'').trim(),unit=String(x?.unit||(band==='FM'?'MHz':'kHz')).trim();return`${n.toLocaleString('tr-TR',{maximumFractionDigits:2})}${unit?` ${unit}`:''}`}
function reminderTimeText(value){const raw=String(value||'').slice(0,5),m=raw.match(/^(\d{2}):(\d{2})$/);return m&&Number(m[1])<=23&&Number(m[2])<=59?raw:''}
function metaText(x,{includeTime=false}={}){const out=[],time=includeTime?reminderTimeText(x?.reminder_time):'';if(time)out.push(time);const band=String(x?.band||'').trim();if(band)out.push(band);const freq=frequencyText(x);if(freq)out.push(freq);return out.join(' · ')}
function miniEmpty(title,body){return `<div class="v38-menu-empty"><span aria-hidden="true">◇</span><b>${esc(title)}</b><p>${esc(body)}</p></div>`}
async function refreshCollections(userId){if(!userId||typeof R.userServices?.loadCollections!=='function')throw new Error('Koleksiyon servisi hazır değil.');return R.userServices.loadCollections(false,userId)}
function setActionBusy(button,busy,label='İşleniyor…'){if(!button?.isConnected)return;button.disabled=!!busy;button.classList.toggle('is-busy',!!busy);if(busy){button.dataset.menuPreviousDesc=button.querySelector('small')?.textContent||'';button.setAttribute('aria-busy','true');const small=button.querySelector('small');if(small)small.textContent=label}else{button.removeAttribute('aria-busy');const small=button.querySelector('small');if(small&&button.dataset.menuPreviousDesc!==undefined)small.textContent=button.dataset.menuPreviousDesc;delete button.dataset.menuPreviousDesc}}
async function favorites(button=null){const userId=activeUserId(),token=lifecycle;if(!userId)return null;setActionBusy(button,true,'Favoriler yenileniyor…');let result;try{result=await refreshCollections(userId)}catch(error){if(activeUserId()===userId&&token===lifecycle){R.reportError?.(error,'menu-collections',{silent:true});R.toast?.('Favoriler yenilenemedi.',{type:'error'})}return null}finally{if(activeUserId()===userId&&token===lifecycle)setActionBusy(button,false)}if(activeUserId()!==userId||token!==lifecycle||!$('#v38Sheet'))return null;const a=ownedRows(result?.favorites??R.favorites,userId);return sheet('Favoriler',`<div class="v38-mini-list">${a.length?a.map(x=>{const meta=metaText(x),note=String(x.note||'').trim();return `<article class="v38-mini"><b>${esc(x.station||'Adı belirtilmemiş yayın')}</b>${meta?`<small>${esc(meta)}</small>`:''}${note?`<p>${esc(note)}</p>`:''}</article>`}).join(''):miniEmpty('Henüz favori yayın yok','Yayın rehberinden bir hedefi favorilere eklediğinde burada görünür.')}</div>`,{view:'favorites',subtitle:`${a.length.toLocaleString('tr-TR')} kayıt`,backAction:'back:favorites'})}
async function reminders(button=null){const userId=activeUserId(),token=lifecycle;if(!userId)return null;setActionBusy(button,true,'Hatırlatıcılar yenileniyor…');let result;try{result=await refreshCollections(userId)}catch(error){if(activeUserId()===userId&&token===lifecycle){R.reportError?.(error,'menu-collections',{silent:true});R.toast?.('Hatırlatıcılar yenilenemedi.',{type:'error'})}return null}finally{if(activeUserId()===userId&&token===lifecycle)setActionBusy(button,false)}if(activeUserId()!==userId||token!==lifecycle||!$('#v38Sheet'))return null;const a=ownedRows(result?.reminders??R.reminders,userId);return sheet('Hatırlatıcılar',`<div class="v38-mini-list">${a.length?a.map(x=>{const meta=metaText(x,{includeTime:true}),station=String(x.station||'Yayın').trim()||'Yayın',enabled=!!x.enabled;return `<article class="v38-mini v38-reminder-row"><div><b>${esc(station)}</b><small>${esc(meta||'Saat ve frekans bilgisi belirtilmemiş')}</small></div><button type="button" class="v38-toggle ${enabled?'on':''}" data-reminder="${esc(x.id)}" data-enabled="${enabled?'1':'0'}" aria-pressed="${enabled?'true':'false'}" aria-label="${esc(station)} hatırlatıcısını ${enabled?'kapat':'aç'}">${enabled?'Açık':'Kapalı'}</button></article>`}).join(''):miniEmpty('Henüz hatırlatıcı yok','Yayın rehberinden bir yayın saati için hatırlatıcı oluşturabilirsin.')}</div>`,{view:'reminders',subtitle:`${a.length.toLocaleString('tr-TR')} kayıt`,backAction:'back:reminders'})}
function syncThemeRow(){const b=$('#v38Sheet [data-action="theme"]');if(!b)return;const night=themeNight(),small=b.querySelector('small'),state=b.querySelector('.v38-menu-state');if(small)small.textContent=night?'Gece görünümü açık':'Açık görünüm açık';if(state)state.textContent=night?'Gece':'Açık';b.setAttribute('aria-pressed',night?'true':'false')}
function syncInstallRow(){const b=$('#v38Sheet [data-action="install"]');if(!b)return;const x=installState(),small=b.querySelector('small'),state=b.querySelector('.v38-menu-state');if(small)small.textContent=x.desc;if(state)state.textContent=x.state;b.disabled=x.installed;b.setAttribute('aria-disabled',x.installed?'true':'false')}
async function syncNow(button){const userId=activeUserId();if(!userId)return null;if(syncFlights.has(userId))return syncFlights.get(userId);if(typeof R.syncOutbox!=='function'){R.toast?.('Senkronizasyon servisi hazır değil.',{type:'error'});return null}const token=lifecycle,flight=(async()=>{setActionBusy(button,true,'Çevrimdışı kayıtlar eşitleniyor…');const state=button?.querySelector('.v38-menu-state');if(state)state.textContent='Çalışıyor';try{const result=await R.syncOutbox();if(activeUserId()!==userId)return result;const synced=Math.max(0,Number(result?.synced)||0),pending=Math.max(0,Number(result?.pending)||0);if(pending>0)R.toast?.(`${pending} çevrimdışı kayıt hâlâ bekliyor. Bağlantıyı kontrol edip yeniden dene.`,{type:'error',duration:5000});else if(synced>0)R.toast?.(`${synced} çevrimdışı kayıt bulutla eşitlendi.`,{type:'success'});else R.toast?.('Bekleyen çevrimdışı kayıt yok.');return result}catch(error){if(activeUserId()===userId){R.reportError?.(error,'menu-offline-sync',{silent:true});R.toast?.('Senkronizasyon tamamlanamadı. Bağlantıyı kontrol edip yeniden dene.',{type:'error',duration:5000})}return null}finally{syncFlights.delete(userId);if(activeUserId()===userId&&token===lifecycle&&button?.isConnected){setActionBusy(button,false);const state=button.querySelector('.v38-menu-state');if(state)state.textContent='Hazır'}}})();syncFlights.set(userId,flight);return flight}
async function action(a,button=null){if(a?.startsWith('route:')){close();return R.router?.go?.(a.slice(6),{source:'menu',historyMode:'push'})}if(a==='back:favorites')return open({focusAction:'favorites',preserveLifecycle:true});if(a==='back:reminders')return open({focusAction:'reminders',preserveLifecycle:true});if(a==='search'){close();return R.openGlobalSearch?.()}if(a==='radio-glossary'){close();return R.radioGlossary?.openAll?.()}if(a==='achievements'){close();return R.openAchievements?.()}if(a==='favorites')return favorites(button);if(a==='reminders')return reminders(button);if(a==='theme'){document.body.classList.toggle('night-mode');document.documentElement.classList.toggle('night');try{localStorage.setItem('radio-night',themeNight()?'1':'0')}catch{}syncThemeRow();return themeNight()}if(a==='sync')return syncNow(button);if(a==='diagnostics'){close();return R.openDiagnostics?.()}if(a==='install'){if(R.pwaInstall?.isStandalone?.())return null;close();return R.installPWA?.()}if(a==='logout'){close();return $('#logoutBtn')?.click()}return null}
function isolateDiagnostics(userId,previousUserId){const next=String(userId||'anonymous');let owner=null;try{owner=localStorage.getItem(DIAG_OWNER_KEY)}catch{}const hasExisting=!!R.diagnostics?.snapshot?.()?.errors?.length,transitioned=owner!==null?owner!==next:!!previousUserId||hasExisting&&next!=='anonymous';if(transitioned){R.diagnostics?.clear?.();$('#foundationDiagOverlay')?.remove();$('#foundationDiag')?.remove()}try{localStorage.setItem(DIAG_OWNER_KEY,next)}catch{}return transitioned}
document.addEventListener('click',async e=>{const target=e.target instanceof Element?e.target:null;if(!target)return;const menuButton=target.closest('[data-menu]');if(menuButton)return open();const a=target.closest('#v38Sheet [data-action]');if(a)return action(a.dataset.action,a);const b=target.closest('#v38Sheet [data-reminder]');if(!b||b.dataset.busy==='1')return;const userId=activeUserId(),reminderId=b.dataset.reminder;if(!userId||!reminderId)return;const enabled=b.dataset.enabled!=='1';b.dataset.busy='1';b.disabled=true;b.setAttribute('aria-busy','true');try{const q=await R.S.from('radio_reminders').update({enabled}).eq('id',reminderId).eq('user_id',userId).select('id,enabled').maybeSingle();if(q.error)throw q.error;if(!q.data)throw new Error('Hatırlatıcı bulunamadı veya bu hesaba ait değil.');if(activeUserId()!==userId||!b.isConnected)return;const applied=!!q.data.enabled,row=(R.reminders||[]).find(x=>x?.user_id===userId&&String(x.id)===String(reminderId));if(row)row.enabled=applied;b.dataset.enabled=applied?'1':'0';b.textContent=applied?'Açık':'Kapalı';b.classList.toggle('on',applied);b.setAttribute('aria-pressed',applied?'true':'false');const station=b.closest('.v38-mini')?.querySelector('b')?.textContent?.trim()||'Yayın';b.setAttribute('aria-label',`${station} hatırlatıcısını ${applied?'kapat':'aç'}`)}catch(error){if(activeUserId()===userId){R.reportError?.(error,'menu-reminder-toggle',{silent:true});R.toast?.('Hatırlatıcı güncellenemedi. Bağlantıyı kontrol edip yeniden dene.',{type:'error'})}}finally{if(activeUserId()===userId&&b.isConnected){delete b.dataset.busy;b.disabled=false;b.removeAttribute('aria-busy')}}},true);
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#v38Sheet')){e.preventDefault();close()}});
R.events?.on?.('route:before',()=>{if($('#v38Sheet'))close({restoreFocus:false})});
R.events?.on?.('pwa:install-ready',syncInstallRow);R.events?.on?.('pwa:installed',syncInstallRow);
R.events?.on?.('auth:changed',x=>{const userId=x?.user?.id||null,changedAccount=!!x?.previousUserId&&x.previousUserId!==userId;isolateDiagnostics(userId,x?.previousUserId||null);if(!x?.authenticated||changedAccount)close({restoreFocus:false})});
menuTriggers(false);R.menuUI={open,close,sheet,favorites,reminders,action,isolateDiagnostics,frequencyText,reminderTimeText,metaText,ownedRows,themeNight,installState,syncNow,get lifecycle(){return lifecycle}};R.features?.register?.('menu-ui',{ready:true,provider:'app-menu-ui'});
})();