(()=>{
const R=window.R;if(!R||R.__nowUI381)return;R.__nowUI381=true;const $=s=>document.querySelector(s),esc=v=>R.esc?R.esc(v):String(v??'');
function ensureTab(){let t=$('#tab-now');if(!t){t=document.createElement('section');t.id='tab-now';t.className='tab-view hidden';const app=$('#appView'),log=$('#tab-log');app?.insertBefore(t,log||app.firstChild)}return t}
function ensure(){const t=ensureTab();let x=$('#v38Now');if(!x){x=document.createElement('div');x.id='v38Now';x.className='v38-now';t.appendChild(x)}return x}
function mode(){const v=R.uiState?.nowMode||R.nowMode||'ALL';return['ALL','SW','MW','FM'].includes(v)?v:'ALL'}
function labelNow(){return R.clock?.format?.(new Date(),{weekday:'long',day:'numeric',month:'long',hour:'2-digit',minute:'2-digit',hourCycle:'h23'})||new Date().toLocaleString('tr-TR')}
function band(e){return e?.mode==='SW'?(e.band||'SW'):(e?.mode||e?.band||'')}
function unit(e){return e?.unit||((e?.mode||e?.band)==='FM'?'MHz':'kHz')}
function freq(e){return `${Number(e?.frequency||0).toLocaleString('tr-TR',{maximumFractionDigits:3})} ${unit(e)}`}
function lang(e){return String(e?.language_content||'').split(/[;/,]/)[0].trim()}
function score(e){return Math.max(1,Math.min(99,Math.round(Number(e?._score??e?._s?.score??e?.probability_score??50))))}
function quality(n){return n>=80?'Çok iyi':n>=65?'İyi':n>=50?'Orta':'Zayıf'}
function candidates(m=mode()){try{const a=R.radioNowCandidates?.(m);if(Array.isArray(a))return a}catch{}try{const a=R.currentSuggestions?.()||[];return m==='ALL'?a:a.filter(x=>x.mode===m)}catch{return[]}}
function item(e){const s=score(e);return `<article class="v38-item" data-quality="${s>=80?'great':s>=65?'good':s>=50?'mid':'low'}"><div class="v38-itemtop"><div><div class="freq">${freq(e)}</div><div class="station">${esc(e.station||'Aday yayın')}</div><div class="meta">${esc([band(e),lang(e)||e.country,e.time_text].filter(Boolean).join(' · '))}</div></div><span class="v38-score">${s}/99<span class="v42-quality-label">${quality(s)}</span></span></div><div class="v38-itemactions"><button class="btn primary" data-listen="${esc(e.id)}">Dinle</button><button class="btn ghost" data-prefill="${esc(e.id)}">Kayıt formuna al</button></div><details><summary>Ayrıntıları göster</summary><div class="v38-detail">${e.country?`Ülke: <b>${esc(e.country)}</b><br>`:''}${e.content_hint?`İçerik: <b>${esc(e.content_hint)}</b><br>`:''}${e.source_doc?`Kaynak: ${esc(e.source_doc)}<br>`:''}${e.time_text?`Yayın penceresi: ${esc(e.time_text)}`:''}</div></details></article>`}
function render(){const root=ensure(),m=mode(),a=candidates(m).slice(0,30);R.nowMode=m;root.innerHTML=`<section class="v38-section"><div class="v38-nowhead"><div class="v38-nowtitle"><h2>Şu An</h2><p>Bozköy · ${esc(labelNow())}</p></div><div class="row-actions"><button class="btn ghost" data-v44search>⌕ Ara</button><button class="btn ghost" data-route="guide">Rehber</button></div></div><div class="v38-filters">${['ALL','SW','MW','FM'].map(x=>`<button class="${m===x?'active':''}" data-now-mode="${x}">${x==='ALL'?'Tümü':x}</button>`).join('')}</div><div class="v38-list">${a.length?a.map(item).join(''):'<div class="v38-empty v42-state">Bu bantta şu anda doğrulanmış aktif yayın yok.</div>'}</div></section>`}
document.addEventListener('click',e=>{const b=e.target.closest('[data-now-mode]');if(!b)return;const v=b.dataset.nowMode;if(!['ALL','SW','MW','FM'].includes(v))return;R.nowMode=v;if(R.uiState)R.uiState.nowMode=v;render()},true);
R.events?.on?.('store:updated',()=>{if(R.router?.current?.()==='now')render()});R.events?.on?.('data:loaded',()=>{if(R.router?.current?.()==='now')render()});
R.nowUI={render,ensure,mode};R.router?.register?.('now',{prepare:ensure,enter:render});R.features?.register?.('now-ui',{ready:true,provider:'app-now-ui'});ensure();
})();