(()=>{
const R=window.R;if(!R||R.__homeUI381)return;R.__homeUI381=true;
const $=s=>document.querySelector(s),C=globalThis.RADIO_APP_CONFIG||{timezone:'Europe/Istanbul'},TZ=C.timezone||'Europe/Istanbul',esc=v=>R.esc?R.esc(v):String(v??''),norm=v=>R.norm?R.norm(v):String(v??'').toLocaleLowerCase('tr-TR');
const BAND_ORDER=['FM','MW','SW1','SW2','SW3','SW4','SW5','SW6','SW7','SW8','SW9','SW10'];
const fallbackPartsFmt=new Intl.DateTimeFormat('en-CA',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}),fallbackLabelFmt=new Intl.DateTimeFormat('tr-TR',{timeZone:TZ,weekday:'long',day:'numeric',month:'long',hour:'2-digit',minute:'2-digit',hourCycle:'h23'});let minuteTimer=null,renderTimer=null;
function ensureTab(){let t=$('#tab-home');if(!t){t=document.createElement('section');t.id='tab-home';t.className='tab-view hidden';const app=$('#appView'),log=$('#tab-log');app?.insertBefore(t,log||app.firstChild)}return t}
function ensure(){const t=ensureTab();let x=$('#v38Home');if(!x){x=document.createElement('div');x.id='v38Home';x.className='v38-home';t.appendChild(x)}return x}
function fallbackParts(date=new Date()){const p=Object.fromEntries(fallbackPartsFmt.formatToParts(date).filter(x=>x.type!=='literal').map(x=>[x.type,x.value]));return{date:`${p.year}-${p.month}-${p.day}`,hour:Number(p.hour),minute:Number(p.minute),second:Number(p.second)}}
function parts(){try{const p=R.clock?.parts?.();if(p&&validIsoDate(p.date)&&Number.isInteger(Number(p.hour))&&Number(p.hour)>=0&&Number(p.hour)<=23)return p}catch{}return fallbackParts()}
function labelNow(){try{const value=R.clock?.format?.(new Date(),{weekday:'long',day:'numeric',month:'long',hour:'2-digit',minute:'2-digit',hourCycle:'h23'});if(value)return value}catch{}return fallbackLabelFmt.format(new Date())}
function originName(){return R.listeningOrigin?.()?.name||C.origin?.name||'Bozköy, Torbalı, İzmir'}
function validIsoDate(value){const raw=String(value||'');if(!/^\d{4}-\d{2}-\d{2}$/.test(raw))return false;const d=new Date(`${raw}T12:00:00Z`);return Number.isFinite(d.getTime())&&d.toISOString().slice(0,10)===raw}
function validTime(value){const m=String(value||'').match(/^(\d{1,2}):(\d{2})(?::(\d{2}))?$/);if(!m)return false;const h=Number(m[1]),min=Number(m[2]),sec=m[3]===undefined?0:Number(m[3]);return Number.isInteger(h)&&h>=0&&h<=23&&Number.isInteger(min)&&min>=0&&min<=59&&Number.isInteger(sec)&&sec>=0&&sec<=59}
function ownedLogs(){const userId=R.me?.id||null;return(Array.isArray(R.logs)?R.logs:[]).filter(x=>!userId||!x?.user_id||x.user_id===userId)}
function signalValue(value){const n=Number(value);return Number.isFinite(n)&&n>=1&&n<=5?n:null}
function band(e){return e?.mode==='SW'?(e.band||'SW'):(e?.mode||e?.band||'')}
function unit(e){return e?.unit||((e?.mode||e?.band)==='FM'?'MHz':'kHz')}
function validCandidate(e){const f=Number(e?.frequency),id=e?.id;if(!e||id===null||id===undefined||String(id).trim()===''||!Number.isFinite(f)||f<=0)return false;if(R.currentPrograms?.receiverCompatible?.(e)===false)return false;return true}
function freq(e){const n=Number(e?.frequency);return `${Number.isFinite(n)&&n>0?n.toLocaleString('tr-TR',{maximumFractionDigits:3}):'—'} ${unit(e)}`}
function lang(e){return String(e?.language_content||e?.language||'').split(/[;/,]/)[0].trim()}
function score(e){const raw=e?._score??e?._s?.score??e?.probability_score;if(raw===null||raw===undefined||raw==='')return null;const n=Number(raw);return Number.isFinite(n)?Math.max(1,Math.min(99,Math.round(n))):null}
function quality(n){return n>=80?'Çok iyi':n>=65?'İyi':n>=50?'Orta':'Zayıf'}
function candidates(mode='ALL'){let rows=[];try{const a=R.radioNowCandidates?.(mode);if(Array.isArray(a))rows=a}catch{}if(!rows.length){try{const a=R.currentSuggestions?.()||[];rows=mode==='ALL'?a:a.filter(x=>x.mode===mode)}catch{rows=[]}}return rows.filter(validCandidate)}
function stationOf(x){return String(x?.station||x?.smart_station||'').trim()}
function split(v){return String(v||'').split(/[/,;]/).map(x=>x.trim()).filter(Boolean)}
function addDays(date,days){const d=new Date(`${date}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10)}
function streak(rows=ownedLogs()){const set=new Set(rows.map(x=>x.date).filter(validIsoDate)),today=R.clock?.today?.()||fallbackParts().date;if(!validIsoDate(today)||!set.size)return 0;let date=set.has(today)?today:addDays(today,-1),n=0;while(set.has(date)&&n<set.size){n++;date=addDays(date,-1)}return n}
function countries(rows=ownedLogs()){return new Set(rows.flatMap(x=>split(x.country)).map(norm).filter(Boolean)).size}
function logMoment(x){if(!validIsoDate(x?.date))return null;const time=validTime(x?.time)?String(x.time).slice(0,8):'00:00:00',normalized=time.length===5?`${time}:00`:time;const stamp=Date.parse(`${x.date}T${normalized}Z`);return Number.isFinite(stamp)?stamp:null}
function latestLog(rows=ownedLogs()){let best=null,bestMoment=-Infinity,bestId='';for(const row of rows){const moment=logMoment(row);if(moment===null)continue;const id=String(row?.id??'');if(moment>bestMoment||(moment===bestMoment&&id.localeCompare(bestId,undefined,{numeric:true})>0)){best=row;bestMoment=moment;bestId=id}}return best}
function readWeather(){try{const x=JSON.parse(localStorage.getItem('radio-space-weather-v41')||'null');return x&&Date.now()-Number(x.savedAt||0)<86400000?x:null}catch{return null}}
function propagationText(){const w=readWeather(),kp=Number(w?.kp),h=parts().hour,phase=h>=7&&h<19?'Gündüz':(h>=19&&h<21||h>=5&&h<7?'Gün-gece sınırı':'Gece');return `${Number.isFinite(kp)?`Kp ${kp.toFixed(1)}`:'Kp —'} · ${phase}`}
function dialPosition(e){const i=BAND_ORDER.indexOf(band(e));return i<0?null:Math.max(2,Math.min(98,i/(BAND_ORDER.length-1)*100))}
function radioConsole(selected,total){const pos=dialPosition(selected),selectedBand=band(selected),needle=Number.isFinite(pos)?`<i class="v42-radio-needle" style="left:${pos}%"></i>`:'';return `<div class="v42-radio-console"><div class="v42-console-id"><span>TECSUN</span><b>R-9012</b><small>12 bantlı saha alıcısı</small></div><div class="v42-radio-dial" aria-label="${esc(selectedBand?`R-9012 bant kadranı; seçili bant ${selectedBand}`:'R-9012 bant kadranı; seçili yayın adayı yok')}"><div class="v42-radio-scale">${BAND_ORDER.map(x=>`<span class="${x===selectedBand?'active':''}">${x}</span>`).join('')}</div>${needle}</div><div class="v42-console-live"><span class="v42-live-dot"></span><b>${Number(total||0).toLocaleString('tr-TR')}</b><small>uygun aday</small></div></div>`}
function weekActivity(logs){const today=R.clock?.today?.()||fallbackParts().date,rows=[],counts=new Map();if(!validIsoDate(today))return'';for(const x of logs){if(validIsoDate(x?.date))counts.set(x.date,(counts.get(x.date)||0)+1)}for(let i=6;i>=0;i--){const date=addDays(today,-i),d=new Date(`${date}T12:00:00Z`),count=counts.get(date)||0,label=new Intl.DateTimeFormat('tr-TR',{weekday:'short',timeZone:'UTC'}).format(d).replace('.','');rows.push({date,count,label})}const max=Math.max(1,...rows.map(x=>x.count)),total=rows.reduce((s,x)=>s+x.count,0);return `<div class="v42-week"><div class="v42-week-head"><div><small>SON 7 GÜN</small><b>Dinleme sıklığı</b></div><span>${total} kayıt</span></div><div class="v42-week-bars">${rows.map(x=>{const height=x.count?Math.max(8,Math.round(x.count/max*100)):0;return `<div class="v42-week-day" title="${esc(x.date)} · ${x.count} kayıt" aria-label="${esc(`${x.date}: ${x.count} kayıt`)}"><b>${x.count||''}</b><i aria-hidden="true"><em style="height:${height}%"></em></i><span>${esc(x.label)}</span></div>`}).join('')}</div></div>`}
function guideReady(){return Array.isArray(R.guideEntries)&&R.guideEntries.length>0}
function primaryCard(e){if(!e){if(!guideReady())return '<div class="v42-empty-card"><b>Yayın rehberi henüz hazır değil</b><span>Rehber verileri hazır olduğunda şu anda denenmeye değer yayınlar burada görünecek.</span><div><button class="btn ghost" data-route="guide">Rehberi aç</button></div></div>';return '<div class="v42-empty-card"><b>Şu anda dinlemeye uygun bir yayın adayı yok</b><span>Yayın rehberini veya yayılım asistanını kontrol edebilirsin.</span><div><button class="btn ghost" data-route="guide">Rehberi aç</button><button class="btn ghost" data-route="propagation">Yayılımı aç</button></div></div>'}const s=score(e),scoreBadge=s===null?'<span class="v42-quality">Puan yok</span>':`<span class="v42-quality q${Math.floor(s/10)}">${s} puan · ${quality(s)}</span>`;return `<article class="v42-primary"><div class="v42-primary-head"><span class="v42-band">${esc(band(e))}</span>${scoreBadge}</div><div class="v42-frequency">${freq(e)}</div><div class="v42-freq-ruler" aria-hidden="true"></div><h3>${esc(e.station||'Yayın adayı')}</h3><p>${esc([lang(e)||e.country,e.time_text].filter(Boolean).join(' · '))}</p><div class="v42-primary-actions"><button class="btn primary" data-listen="${esc(e.id)}">Dinlemeye başla</button><button class="btn ghost" data-route="now">Diğer yayınlar</button></div></article>`}
function logFrequency(x){const f=Number(x?.frequency);if(!Number.isFinite(f)||f<=0)return'';const b=String(x?.band||'').trim(),u=b==='FM'?'MHz':'kHz';return `${f.toLocaleString('tr-TR',{maximumFractionDigits:3})} ${u}`}
function lastCard(last,hasLogs){if(!last)return hasLogs?'<div class="v42-empty-card"><b>Son kayıt tarihi okunamadı</b><span>Günlükteki eski veya bozuk tarihli kayıtları düzenlediğinde son kayıt özeti yeniden oluşturulur.</span></div>':'<div class="v42-empty-card"><b>Henüz kayıt yok</b><span>İlk yayını kaydettiğinde kişisel dinleme geçmişin burada oluşmaya başlayacak.</span></div>';const lastSignal=signalValue(last.signal_strength),meta=[last.band,logFrequency(last),last.language,lastSignal?`${lastSignal}/5`:null].filter(Boolean).join(' · '),body=`<div><small>Son kayıt</small><b>${esc(stationOf(last)||[last.band,logFrequency(last)].filter(Boolean).join(' ')||'Dinleme kaydı')}</b><span>${esc(meta)}</span></div><i>›</i>`;return last.id===null||last.id===undefined||String(last.id).trim()===''?`<div class="v42-last">${body}</div>`:`<button class="v42-last" data-log="${esc(last.id)}" aria-label="Son kaydı aç: ${esc(stationOf(last)||logFrequency(last)||'dinleme kaydı')}">${body}</button>`}
function render(){const root=ensure(),all=candidates('ALL'),a=all.slice(0,3),p=parts(),logs=ownedLogs(),today=validIsoDate(p.date)?logs.filter(x=>x.date===p.date):[],last=latestLog(logs),g=p.hour<12?'Günaydın':p.hour<18?'İyi günler':'İyi akşamlar',where=originName();root.innerHTML=`<div class="v42-home"><section class="v42-home-hero"><div class="v42-home-top"><div><span class="v42-kicker">${esc(where)} · ${esc(labelNow())}</span><h2>${g}</h2><p>Radyoyu açtığında, önce hangi yayınları denemeye değer olduğunu burada görebilirsin.</p></div><button class="v42-search-button" data-v44search aria-label="Ara"><span>⌕</span> Ara</button></div><div class="v42-home-grid">${primaryCard(a[0])}<button class="v42-prop-card" data-route="propagation"><span class="v42-prop-icon">◌</span><div><small>Yayılım</small><b>${esc(propagationText())}</b><span>Koşulları ve bant sıralamasını gör</span></div><i>›</i></button></div>${radioConsole(a[0],all.length)}</section>${a.length>1?`<section class="v42-section v42-onair-section"><div class="v42-section-head"><div><span class="v42-section-kicker">ŞİMDİ DİNLENEBİLİR</span><h3>Diğer uygun adaylar</h3><p>Tek dokunuşla dinlemeye başla.</p></div><button class="v42-link" data-route="now">Tümünü gör</button></div><div class="v42-alt-grid">${a.slice(1).map(e=>{const s=score(e),label=[band(e),freq(e),e.station||'Yayın adayı'].join(' · ');return `<button class="v42-alt" data-listen="${esc(e.id)}" aria-label="Dinlemeye başla: ${esc(label)}"><span class="v42-alt-band">${esc(band(e))}</span><div><b>${freq(e)}</b><span>${esc(e.station||'Yayın adayı')}</span><small>${esc(lang(e)||e.country||'')}</small></div><em>${s===null?'—':s}</em></button>`}).join('')}</div></section>`:''}<section class="v42-section v42-journal-section"><div class="v42-section-head"><div><span class="v42-section-kicker">KİŞİSEL SAHA GÜNLÜĞÜ</span><h3>Dinleme geçmişin</h3><p>Kayıtların biriktikçe kişisel alım profilin güçlenir.</p></div><button class="v42-link" data-route="log">Günlüğü aç</button></div><div class="v42-dashboard"><div><b>${today.length}</b><span>bugünkü kayıt</span></div><div><b>${countries(logs)}</b><span>ülke</span></div><div><b>${streak(logs)}</b><span>ardışık gün</span></div></div>${weekActivity(logs)}${lastCard(last,logs.length>0)}</section></div>`;return root}
function stopMinuteRefresh(){if(minuteTimer!==null){clearTimeout(minuteTimer);minuteTimer=null}}
function scheduleMinuteRefresh(){stopMinuteRefresh();if(R.router?.current?.()!=='home'||document.hidden)return;const delay=Math.max(250,60000-(Date.now()%60000)+75);minuteTimer=setTimeout(()=>{minuteTimer=null;if(R.router?.current?.()==='home'&&!document.hidden){render();scheduleMinuteRefresh()}},delay)}
function scheduleRender(delay=0){if(R.router?.current?.()!=='home')return;if(renderTimer!==null)clearTimeout(renderTimer);renderTimer=setTimeout(()=>{renderTimer=null;if(R.router?.current?.()==='home')render()},delay)}
function enter(){render();scheduleMinuteRefresh()}
R.events?.on?.('store:updated',()=>scheduleRender());R.events?.on?.('guide:data-ready',()=>scheduleRender());R.events?.on?.('user:settings',()=>scheduleRender());R.events?.on?.('auth:changed',()=>scheduleRender());R.events?.on?.('route:changed',x=>{if(x?.to==='home')scheduleMinuteRefresh();else if(x?.from==='home')stopMinuteRefresh()});
document.addEventListener('visibilitychange',()=>{if(document.hidden)stopMinuteRefresh();else if(R.router?.current?.()==='home'){render();scheduleMinuteRefresh()}});
R.homeUI={render,ensure,candidates,ownedLogs,score,validCandidate,validIsoDate,validTime,signalValue,streak,weekActivity,latestLog,dialPosition,guideReady,scheduleMinuteRefresh,stopMinuteRefresh};R.router?.register?.('home',{prepare:ensure,enter});R.features?.register?.('home-ui',{ready:true,provider:'app-home-ui'});ensure();
})();