(()=>{
const R=window.R;if(!R||R.__appShell375)return;R.__appShell375=true;const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const C=globalThis.RADIO_APP_CONFIG||{timezone:'Europe/Istanbul'};const esc=v=>R.esc?R.esc(v):String(v??'');const norm=v=>R.norm?R.norm(v):String(v??'').toLocaleLowerCase('tr-TR');
let nowMode=R.uiState?.nowMode||'ALL',activeListen=null;
function css(href,key){if(document.querySelector(`link[data-${key}]`))return;const l=document.createElement('link');l.rel='stylesheet';l.href=href;l.dataset[key]='1';document.head.appendChild(l)}
css('v38-ux-cleanup.css','appShellCss');css('v42-design-system.css','appShellDesignCss');
function ensureTab(name){let t=$(`#tab-${name}`);if(!t){t=document.createElement('section');t.id=`tab-${name}`;t.className='tab-view hidden';const app=$('#appView'),log=$('#tab-log');app?.insertBefore(t,log||app.firstChild)}return t}
function ensureHome(){const t=ensureTab('home');let x=$('#v38Home');if(!x){x=document.createElement('div');x.id='v38Home';x.className='v38-home';t.appendChild(x)}return x}
function ensureNow(){const t=ensureTab('now');let x=$('#v38Now');if(!x){x=document.createElement('div');x.id='v38Now';x.className='v38-now';t.appendChild(x)}return x}
function parts(){return R.clock?.parts?.()||{date:new Date().toLocaleDateString('en-CA'),hour:new Date().getHours()}}
function labelNow(){return R.clock?.format?.(new Date(),{weekday:'long',day:'numeric',month:'long',hour:'2-digit',minute:'2-digit',hourCycle:'h23'})||new Date().toLocaleString('tr-TR')}
function band(e){return e?.mode==='SW'?(e.band||'SW'):(e?.mode||e?.band||'')}
function unit(e){return e?.unit||((e?.mode||e?.band)==='FM'?'MHz':'kHz')}
function freq(e){return `${Number(e?.frequency||0).toLocaleString('tr-TR',{maximumFractionDigits:3})} ${unit(e)}`}
function lang(e){return String(e?.language_content||'').split(/[;/,]/)[0].trim()}
function score(e){return Math.max(1,Math.min(99,Math.round(Number(e?._score??e?._s?.score??e?.probability_score??50))))}
function quality(n){return n>=80?'Çok iyi':n>=65?'İyi':n>=50?'Orta':'Zayıf'}
function candidates(mode='ALL'){try{const a=R.radioNowCandidates?.(mode);if(Array.isArray(a))return a}catch{}try{const a=R.currentSuggestions?.()||[];return mode==='ALL'?a:a.filter(x=>x.mode===mode)}catch{return[]}}
function byId(id){return (R.guideEntries||[]).find(x=>String(x.id)===String(id))||candidates('ALL').find(x=>String(x.id)===String(id))}
function stationOf(x){return String(x?.station||x?.smart_station||'').trim()}
function split(v){return String(v||'').split(/[/,;]/).map(x=>x.trim()).filter(Boolean)}
function streak(){const set=new Set((R.logs||[]).map(x=>x.date).filter(Boolean));let n=0;const today=R.clock?.today?.()||new Date().toLocaleDateString('en-CA');for(let i=0;i<366;i++){const d=new Date(today+'T12:00:00Z');d.setUTCDate(d.getUTCDate()-i);const k=d.toISOString().slice(0,10);if(set.has(k))n++;else if(i===0)continue;else break}return n}
function countries(){return new Set((R.logs||[]).flatMap(x=>split(x.country)).map(norm).filter(Boolean)).size}
function readWeather(){try{const x=JSON.parse(localStorage.getItem('radio-space-weather-v41')||'null');return x&&Date.now()-Number(x.savedAt||0)<86400000?x:null}catch{return null}}
function propagationText(){const w=readWeather(),kp=Number(w?.kp),h=parts().hour,phase=h>=7&&h<19?'Gündüz':(h>=19&&h<21||h>=5&&h<7?'Gray-line yakın':'Gece');return `${Number.isFinite(kp)?`Kp ${kp.toFixed(1)}`:'Kp —'} · ${phase}`}
function primaryCard(e){if(!e)return `<div class=v42-empty-card><b>Şu dakika için aktif aday yok</b><span>Yayın rehberini veya Yayılım Asistanı'nı kontrol edebilirsin.</span><div><button class="btn ghost" data-route="guide">Rehberi aç</button><button class="btn ghost" data-route="propagation">Yayılımı aç</button></div></div>`;const s=score(e);return `<article class=v42-primary><div class=v42-primary-head><span class=v42-band>${esc(band(e))}</span><span class="v42-quality q${Math.floor(s/10)}">${s} · ${quality(s)}</span></div><div class=v42-frequency>${freq(e)}</div><h3>${esc(e.station||'Aday yayın')}</h3><p>${esc([lang(e)||e.country,e.time_text].filter(Boolean).join(' · '))}</p><div class=v42-primary-actions><button class="btn primary" data-listen="${esc(e.id)}">Dinlemeye başla</button><button class="btn ghost" data-route="now">Diğer yayınlar</button></div></article>`}
function renderHome(){const root=ensureHome(),a=candidates('ALL').slice(0,3),p=parts(),logs=R.logs||[],today=logs.filter(x=>x.date===p.date),last=logs[0],g=p.hour<12?'Günaydın':p.hour<18?'İyi günler':'İyi akşamlar';root.innerHTML=`<div class=v42-home><section class=v42-home-hero><div class=v42-home-top><div><span class=v42-kicker>BOZKÖY · TORBALI · ${esc(labelNow())}</span><h2>${g}</h2><p>Radyoyu açtığında önce neyi denemen gerektiğini burada gör.</p></div><button class=v42-search-button data-v44search aria-label="Ara"><span>⌕</span> Ara</button></div><div class=v42-home-grid>${primaryCard(a[0])}<button class=v42-prop-card data-route="propagation"><span class=v42-prop-icon>◌</span><div><small>Yayılım</small><b>${esc(propagationText())}</b><span>Koşulları ve bant sıralamasını gör</span></div><i>›</i></button></div></section>${a.length>1?`<section class=v42-section><div class=v42-section-head><div><h3>Diğer iyi adaylar</h3><p>Tek dokunuşla Dinleme Modu'na geç</p></div><button class=v42-link data-route="now">Tümünü gör</button></div><div class=v42-alt-grid>${a.slice(1).map(e=>{const s=score(e);return`<button class=v42-alt data-listen="${esc(e.id)}"><span class=v42-alt-band>${esc(band(e))}</span><div><b>${freq(e)}</b><span>${esc(e.station||'Aday yayın')}</span><small>${esc(lang(e)||e.country||'')}</small></div><em>${s}</em></button>`}).join('')}</div></section>`:''}<section class=v42-section><div class=v42-dashboard><div><b>${today.length}</b><span>bugünkü kayıt</span></div><div><b>${countries()}</b><span>ülke</span></div><div><b>${streak()}</b><span>günlük seri</span></div></div>${last?`<button class=v42-last data-log="${last.id}"><div><small>Son kayıt</small><b>${esc(stationOf(last)||`${last.band||''} ${last.frequency||''}`)}</b><span>${esc([last.band,last.frequency!=null?Number(last.frequency).toLocaleString('tr-TR',{maximumFractionDigits:3}):'',last.language,last.signal_strength?`${last.signal_strength}/5`:null].filter(Boolean).join(' · '))}</span></div><i>›</i></button>`:'<div class=v42-empty-card><b>Henüz kayıt yok</b><span>İlk sinyali yakaladığında kişisel hafızan burada büyümeye başlayacak.</span></div>'}</section></div>`}
function nowItem(e){const s=score(e);return `<article class=v38-item data-quality="${s>=80?'great':s>=65?'good':s>=50?'mid':'low'}"><div class=v38-itemtop><div><div class=freq>${freq(e)}</div><div class=station>${esc(e.station||'Aday yayın')}</div><div class=meta>${esc([band(e),lang(e)||e.country,e.time_text].filter(Boolean).join(' · '))}</div></div><span class=v38-score>${s}/99<span class=v42-quality-label>${quality(s)}</span></span></div><div class=v38-itemactions><button class="btn primary" data-listen="${esc(e.id)}">Dinle</button><button class="btn ghost" data-prefill="${esc(e.id)}">Kayıt formuna al</button></div><details><summary>Ayrıntıları göster</summary><div class=v38-detail>${e.country?`Ülke: <b>${esc(e.country)}</b><br>`:''}${e.content_hint?`İçerik: <b>${esc(e.content_hint)}</b><br>`:''}${e.source_doc?`Kaynak: ${esc(e.source_doc)}<br>`:''}${e.time_text?`Yayın penceresi: ${esc(e.time_text)}`:''}</div></details></article>`}
function renderNow(){const root=ensureNow(),a=candidates(nowMode).slice(0,30);root.innerHTML=`<section class=v38-section><div class=v38-nowhead><div class=v38-nowtitle><h2>Şu An</h2><p>Bozköy · ${esc(labelNow())}</p></div><div class="row-actions"><button class="btn ghost" data-v44search>⌕ Ara</button><button class="btn ghost" data-route="guide">Rehber</button></div></div><div class=v38-filters>${['ALL','SW','MW','FM'].map(m=>`<button class="${nowMode===m?'active':''}" data-now-mode="${m}">${m==='ALL'?'Tümü':m}</button>`).join('')}</div><div class=v38-list>${a.length?a.map(nowItem).join(''):'<div class="v38-empty v42-state">Bu bantta şu anda doğrulanmış aktif yayın yok.</div>'}</div></section>`}
function dockActive(route){$$('#v38Dock [data-route]').forEach(b=>b.classList.toggle('active',b.dataset.route===route))}
function ensureDock(){document.querySelector('#v33Dock')?.remove();document.querySelector('.v22-bottom')?.remove();document.querySelector('.v31-dock')?.remove();if(!R.me||$('#appView')?.classList.contains('hidden')){$('#v38Dock')?.remove();return}let d=$('#v38Dock');if(d)return d;d=document.createElement('nav');d.id='v38Dock';d.className='v38-dock';d.innerHTML=`<button data-route="home"><i>⌂</i>Ana Sayfa</button><button data-route="now"><i>◉</i>Şu An</button><button class=plus data-quick><i>＋</i>Kayıt</button><button data-route="log"><i>▤</i>Günlük</button><button data-menu><i>≡</i>Menü</button>`;document.body.appendChild(d);dockActive(R.router?.current?.()||'home');return d}
function closeSheet(){$('#v38Overlay')?.remove();$('#v38Sheet')?.remove()}
function sheet(title,body){closeSheet();const o=document.createElement('div');o.id='v38Overlay';o.className='v38-overlay';o.onclick=closeSheet;const s=document.createElement('div');s.id='v38Sheet';s.className='v38-sheet';s.innerHTML=`<div class=v38-sheethead><h2>${esc(title)}</h2><button class=v38-close>×</button></div>${body}`;document.body.append(o,s);s.querySelector('.v38-close').onclick=closeSheet;R.events?.emit?.('menu:opened',{sheet:s,title});return s}
function row(a,b,action){return `<button class=v38-menu-row data-action="${action}"><span style="display:block;color:inherit;font-size:inherit"><b>${esc(a)}</b><small>${esc(b)}</small></span><span>›</span></button>`}
function openMenu(){sheet('Menü',`<details class=v38-menu-group open><summary>Koleksiyon</summary><div class=v38-menu-list>${row('Radyo Hafızası','İstasyon, frekans ve ülke profilleri','route:memory')}${row('Radyo Atlası','Ülke, yön ve dinleme geçmişi','route:atlas')}${row('QSL','Reception report ve cevaplar','route:qsl')}${row('Başarılar','Rozet ve koleksiyon ilerlemesi','achievements')}${row('Favoriler','Kaydettiğin yayın hedefleri','favorites')}</div></details><details class=v38-menu-group><summary>Araçlar</summary><div class=v38-menu-list>${row('Yayılım Asistanı','Gray-line, uzay havası ve kişisel bant tahmini','route:propagation')}${row('AI Ses Analizi','Ses, dil ve istasyon adayları','route:ai')}${row('Yayın Rehberi','Frekans ve yayın pencereleri','route:guide')}${row('Akıllı Dinleme','Oturumlar, gizemler ve kalibrasyon','route:smart')}${row('Ses Kaydı','Radyo sesini kaydet ve yazıya çevir','route:audio')}${row('Konum Haritası','GPS eklenen dinleme kayıtları','route:map')}</div></details><details class=v38-menu-group><summary>Geçmiş</summary><div class=v38-menu-list>${row('Günlük','Tüm dinleme kayıtların','route:log')}${row('Takvim','Dinleme günlerini gör','route:calendar')}${row('İstatistikler','Bant, dil ve çekim analizi','route:analysis')}</div></details><details class=v38-menu-group><summary>Ayarlar</summary><div class=v38-menu-list>${row('Hatırlatıcılar','Yayın saatlerini takip et','reminders')}${row('Görünüm','Açık / gece modu','theme')}${row('Senkronizasyon','Offline kuyruğu buluta gönder','sync')}${row('Sistem Durumu','Router, veri ve PWA tanıları','diagnostics')}${row('Uygulamayı kur','PWA kurulumunu başlat','install')}</div></details><div class=v38-menu-footer><button class="btn ghost" data-action="logout">Çıkış</button></div>`)}
async function favorites(){let a=R.favorites||[];if(!a.length&&R.me){const q=await R.S.from('radio_favorites').select('*').eq('user_id',R.me.id).order('created_at',{ascending:false});if(!q.error){a=q.data||[];R.favorites=a}}sheet('Favoriler',`<div class=v38-mini-list>${a.length?a.map(x=>`<div class=v38-mini><b>${esc(x.station||'İsimsiz yayın')}</b><small>${esc(x.band||'')} · ${Number(x.frequency).toLocaleString('tr-TR')} ${esc(x.unit||'')} ${x.note?'· '+esc(x.note):''}</small></div>`).join(''):'<div class=v38-empty>Henüz favori yayın yok.</div>'}</div>`)}
async function reminders(){let a=[];if(R.me){const q=await R.S.from('radio_reminders').select('*').eq('user_id',R.me.id).order('reminder_time');if(!q.error){a=q.data||[];R.reminders=a}}sheet('Hatırlatıcılar',`<div class=v38-mini-list>${a.length?a.map(x=>`<div class=v38-mini style="display:flex;justify-content:space-between;gap:8px;align-items:center"><div><b>${esc(x.station||'Yayın')}</b><small>${String(x.reminder_time||'').slice(0,5)} · ${esc(x.band||'')} ${Number(x.frequency).toLocaleString('tr-TR')} ${esc(x.unit||'')}</small></div><button class="v38-toggle ${x.enabled?'on':''}" data-reminder="${x.id}" data-enabled="${x.enabled?'1':'0'}">${x.enabled?'Açık':'Kapalı'}</button></div>`).join(''):'<div class=v38-empty>Henüz hatırlatıcı yok.</div>'}</div>`)}
async function quick(){let sig=3;const s=sheet('Hızlı kayıt',`<div class=form-grid><label>Bant<select id=qBand>${(R.B||[]).map(b=>`<option>${b}</option>`).join('')}</select></label><label>Frekans<input id=qFreq type=number step=.001 placeholder="Frekans"></label><label class=span2>İstasyon<input id=qStation placeholder="İsteğe bağlı"></label></div><div style="margin-top:10px"><div class=small>Sinyal</div><div id=qSignal class=v38-signal style="margin-top:6px">${[1,2,3,4,5].map(x=>`<button type=button data-qsig=${x} class="${x===sig?'active':''}">${x}</button>`).join('')}</div></div><details class=v38-menu-group style="margin-top:10px"><summary>Not ekle</summary><div style="padding:0 12px 12px"><input id=qNote placeholder="Duyulan kelime / kısa not"></div></details><button id=qSave class="btn primary" style="width:100%;margin-top:12px;min-height:45px">Kaydet</button><button id=qDetail class="btn ghost" style="width:100%;margin-top:7px">Ayrıntılı kayıt aç</button><p id=qMsg class=small style="text-align:center"></p>`);s.querySelectorAll('[data-qsig]').forEach(b=>b.onclick=()=>{sig=Number(b.dataset.qsig);s.querySelectorAll('[data-qsig]').forEach(x=>x.classList.toggle('active',Number(x.dataset.qsig)===sig))});s.querySelector('#qSave').onclick=async()=>{const b=s.querySelector('#qBand').value,f=Number(s.querySelector('#qFreq').value);if(!f)return s.querySelector('#qMsg').textContent='Frekans gir.';const body={user_id:R.me.id,date:R.clock?.today?.()||new Date().toLocaleDateString('en-CA'),time:R.clock?.time?.()||new Date().toTimeString().slice(0,5),band:b,frequency:f,station:s.querySelector('#qStation').value.trim()||null,location:'Bozköy, Torbalı, İzmir',signal_strength:sig,notes:s.querySelector('#qNote')?.value.trim()||null,status:'candidate',qsl_status:'none',source:'manual'};if(!navigator.onLine&&R.queueLog)await R.queueLog(body);else{const q=await R.S.from('radio_logs').insert(body);if(q.error)return s.querySelector('#qMsg').textContent=q.error.message;await R.load()}closeSheet()};s.querySelector('#qDetail').onclick=()=>{closeSheet();R.reset?.();R.router?.go?.('log',{source:'quick-detail'});$('#tab-log')?.classList.add('v38-form-open')}}
function ensureLogbar(){const tab=$('#tab-log'),records=tab?.querySelector('.records-card');if(!tab||!records||$('#v38Logbar'))return;const b=document.createElement('div');b.id='v38Logbar';b.className='v38-logbar';b.innerHTML=`<div><h2>Günlük</h2><p>Kayıt kartına dokunarak ayrıntıları aç.</p></div><div class=v38-logactions><button class="btn primary" data-detail-new>Yeni kayıt</button><button class="btn ghost" data-log-filters>Filtre</button></div>`;records.parentElement?.insertBefore(b,records)}
function decorateLog(){ensureLogbar();$$('#records .record-card').forEach(c=>c.classList.remove('v38-expanded'))}
function ensureTopSearch(){const top=$('.topbar');if(!top||top.querySelector('[data-v44search]'))return;const b=document.createElement('button');b.type='button';b.className='v42-top-search';b.dataset.v44search='1';b.innerHTML='<span>⌕</span><b>Ara</b>';top.insertBefore(b,$('#userBox')||null)}
function netChip(){let c=$('#v42Net');if(!c){c=document.createElement('div');c.id='v42Net';c.className='v42-net';document.body.appendChild(c)}c.classList.toggle('offline',!navigator.onLine);c.innerHTML=navigator.onLine?'<span></span> Çevrimiçi':'<span></span> Çevrimdışı';c.hidden=navigator.onLine}
function removeMini(){$('#v42MiniListen')?.remove()}
function showMini(){if(!activeListen||$('#v38Listen'))return removeMini();let m=$('#v42MiniListen');if(!m){m=document.createElement('div');m.id='v42MiniListen';m.className='v42-mini-listen';document.body.appendChild(m)}m.innerHTML=`<button class=v42-mini-main data-resume-listen><span class=v42-mini-dot></span><div><small>Dinleme devam ediyor</small><b>${esc(band(activeListen))} · ${freq(activeListen)}</b><span>${esc(activeListen.station||'Aday yayın')}</span></div></button><button class=v42-mini-close data-stop-listen aria-label="Dinlemeyi kapat">×</button>`}
function enhanceListen(){const x=$('#v38Listen');if(!x||x.querySelector('[data-minimize-listen]'))return;const top=x.querySelector('.v38-listentop'),close=top?.querySelector('.v38-listenclose');if(!top)return;const b=document.createElement('button');b.className='v42-listen-min';b.dataset.minimizeListen='1';b.textContent='Küçült';top.insertBefore(b,close||null)}
const openListen=R.v38OpenListen,closeListen=R.v38CloseListen;if(typeof openListen==='function')R.v38OpenListen=e=>{activeListen=e||null;removeMini();const out=openListen(e);setTimeout(enhanceListen,0);R.events?.emit?.('listening:opened',{entry:e});return out};if(typeof closeListen==='function')R.v38CloseListen=()=>{activeListen=null;removeMini();const out=closeListen();R.events?.emit?.('listening:closed');return out};
async function action(a){if(a?.startsWith('route:')){closeSheet();return R.router?.go?.(a.slice(6),{source:'menu'})}if(a==='achievements'){closeSheet();return setTimeout(()=>$('#v24All')?.click(),50)}if(a==='favorites')return favorites();if(a==='reminders')return reminders();if(a==='theme'){document.body.classList.toggle('night-mode');document.documentElement.classList.toggle('night');localStorage.setItem('radio-night',document.body.classList.contains('night-mode')?'1':'0');return}if(a==='sync'){await R.syncOutbox?.();return R.toast?.('Senkronizasyon kontrol edildi.')}if(a==='diagnostics'){closeSheet();return R.openDiagnostics?.()}if(a==='install'){if(R.installPrompt){await R.installPrompt.prompt();try{await R.installPrompt.userChoice}catch{}R.installPrompt=null}else R.toast?.('Kurulum seçeneği şu anda hazır değil.');return}if(a==='logout'){closeSheet();$('#logoutBtn')?.click()}}
document.addEventListener('click',async e=>{const route=e.target.closest('[data-route]');if(route){R.__nextNavigationHistory='push';return R.router?.go?.(route.dataset.route,{source:'ui',historyMode:'push'})}if(e.target.closest('[data-menu]'))return openMenu();if(e.target.closest('[data-quick]'))return quick();const m=e.target.closest('[data-now-mode]');if(m){nowMode=m.dataset.nowMode;R.uiState&&(R.uiState.nowMode=nowMode);return renderNow()}const l=e.target.closest('[data-listen]');if(l)return R.v38OpenListen?.(byId(l.dataset.listen));const p=e.target.closest('[data-prefill]');if(p){const x=byId(p.dataset.prefill);if(x&&R.prefillGuide)R.prefillGuide(x);return}const log=e.target.closest('[data-log]');if(log){R.edit?.(log.dataset.log);return R.router?.go?.('log',{source:'home-log'})}const a=e.target.closest('[data-action]');if(a)return action(a.dataset.action);const r=e.target.closest('[data-reminder]');if(r){const enabled=r.dataset.enabled!=='1',q=await R.S.from('radio_reminders').update({enabled}).eq('id',r.dataset.reminder).eq('user_id',R.me.id);if(!q.error){r.dataset.enabled=enabled?'1':'0';r.textContent=enabled?'Açık':'Kapalı';r.classList.toggle('on',enabled)}return}if(e.target.closest('[data-detail-new]')){R.reset?.();$('#tab-log')?.classList.add('v38-form-open');return}if(e.target.closest('[data-log-filters]'))return $('#tab-log .records-card')?.classList.toggle('v38-filters-open');if(e.target.closest('[data-minimize-listen]')){e.preventDefault();e.stopPropagation();$('#v38Listen')?.remove();showMini();R.events?.emit?.('listening:minimized',{entry:activeListen});return}if(e.target.closest('[data-resume-listen]'))return R.v38OpenListen?.(activeListen);if(e.target.closest('[data-stop-listen]')){activeListen=null;removeMini();return}const top=e.target.closest('#records .record-card .record-top');if(top&&!e.target.closest('button,a,input,select'))top.closest('.record-card')?.classList.toggle('v38-expanded')},true);
function refresh(route=R.router?.current?.()){ensureDock();ensureTopSearch();netChip();if(route==='home')renderHome();if(route==='now')renderNow();if(route==='log')decorateLog();dockActive(route);if(activeListen&&!$('#v38Listen'))showMini();if($('#v38Listen'))enhanceListen()}
R.events?.on?.('route:changed',x=>refresh(x?.to));R.events?.on?.('store:updated',()=>refresh());R.events?.on?.('data:loaded',()=>refresh());R.events?.on?.('auth:changed',x=>{if(x?.authenticated)setTimeout(()=>refresh(),0);else{$('#v38Dock')?.remove();closeSheet();removeMini()}});R.events?.on?.('render:all',()=>{if(R.router?.current?.()==='log')decorateLog()});
window.addEventListener('online',()=>{netChip();R.toast?.('Bağlantı geri geldi. Senkronizasyon devam edebilir.')});window.addEventListener('offline',netChip);
R.shell={renderHome,renderNow,openMenu,quick,refresh};R.router?.register?.('home',{prepare:ensureHome,enter:renderHome});R.router?.register?.('now',{prepare:ensureNow,enter:renderNow});R.features?.register?.('shell',{ready:true,provider:'app-shell'});
ensureHome();ensureNow();setTimeout(()=>refresh(),80);
})();
