(()=>{
const R=window.R;if(!R||R.__backup376)return;R.__backup376=true;const $=s=>document.querySelector(s);const C=globalThis.RADIO_APP_CONFIG||{timezone:'Europe/Istanbul',version:'3.8.5'};const toast=v=>R.toast?R.toast(v):alert(v);const csvCell=v=>'"'+String(v??'').replaceAll('"','""')+'"';
const PAGE_SIZE=1000,MAX_ROWS=50000,AUDIO_PAGE_SIZE=100,MAX_AUDIO=10000;
function today(){return R.clock?.today?.()||new Intl.DateTimeFormat('en-CA',{timeZone:C.timezone||'Europe/Istanbul'}).format(new Date())}
async function fetchUserRows(table,order='created_at'){if(!R.me?.id)return[];const out=[];for(let from=0;from<MAX_ROWS;from+=PAGE_SIZE){const q=await R.S.from(table).select('*').eq('user_id',R.me.id).order(order,{ascending:false}).order('id',{ascending:false}).range(from,from+PAGE_SIZE-1);if(q.error)throw q.error;const rows=q.data||[];out.push(...rows);if(rows.length<PAGE_SIZE)return out}throw new Error(`${table} yedekleme güvenlik sınırını aştı.`)}
async function fetchSettings(){if(!R.me?.id)return null;const q=await R.S.from('radio_user_settings').select('*').eq('user_id',R.me.id).maybeSingle();if(q.error)throw q.error;return q.data||null}
async function fetchAudioManifest(){if(!R.me?.id)return[];const out=[];for(let offset=0;offset<MAX_AUDIO;offset+=AUDIO_PAGE_SIZE){const q=await R.S.storage.from('radio-audio').list(R.me.id,{limit:AUDIO_PAGE_SIZE,offset,sortBy:{column:'created_at',order:'desc'}});if(q.error)throw q.error;const rows=q.data||[];out.push(...rows.map(x=>({path:`${R.me.id}/${x.name}`,created_at:x.created_at,size:x.metadata?.size??null,mimetype:x.metadata?.mimetype??null})));if(rows.length<AUDIO_PAGE_SIZE)return out}throw new Error('Ses dosyası listesi yedekleme güvenlik sınırını aştı.')}
async function fetchOfflineOutbox(){if(!R.me?.id||typeof R.offline?.list!=='function')return[];const rows=await R.offline.list();return(rows||[]).filter(x=>(x?.user_id||x?.body?.user_id)===R.me.id).map(x=>({id:x.id,queue_id:x.queue_id||x.body?.offline_queue_id||null,queued_at:x.queued_at||null,body:x.body||null}))}
async function fullMetadata(){if(!R.me?.id)throw new Error('Yedek almak için giriş yapmalısın.');await R.load?.();const [settings,audio,favorites,reminders,achievements,calibrations,sessions,attempts,analyses,offlineOutbox]=await Promise.all([
 fetchSettings(),fetchAudioManifest(),fetchUserRows('radio_favorites'),fetchUserRows('radio_reminders'),fetchUserRows('radio_achievements','unlocked_at'),fetchUserRows('radio_dial_calibrations'),fetchUserRows('radio_listening_sessions','started_at'),fetchUserRows('radio_session_attempts','attempted_at'),fetchUserRows('radio_ai_analyses'),fetchOfflineOutbox()
]);return{version:C.version,exported_at:new Date().toISOString(),timezone:C.timezone,audio_files_embedded:false,logs:R.logs||[],favorites,reminders,achievements,dial_calibrations:calibrations,listening_sessions:sessions,session_attempts:attempts,ai_analyses:analyses,settings,audio_manifest:audio,offline_outbox:offlineOutbox}}
function install(){const csv=$('#csvBtn'),json=$('#jsonBtn');if(csv&&!csv.dataset.appBackup){csv.dataset.appBackup='1';csv.onclick=async()=>{try{await R.load?.();const keys=['created_at','date','time','band','frequency','station','language','country','content_type','program','location','latitude','longitude','signal_strength','status','antenna_direction','antenna_angle','dial_position','transcript','smart_language','smart_station','smart_program','smart_confidence','audio_path','audio_duration_seconds','qsl_status','qsl_sent_at','qsl_received_at','qsl_contact','qsl_notes','source','session_id','offline_queue_id','is_mystery','mystery_status','mystery_notes','notes'];const text='\ufeff'+[keys.join(';'),...(R.logs||[]).map(x=>keys.map(k=>csvCell(k==='time'?String(x[k]||'').slice(0,5):x[k])).join(';'))].join('\n');R.download?.(`radyo-kayitlari-${today()}.csv`,text,'text/csv;charset=utf-8')}catch(error){R.reportError?.(error,'backup-csv',{silent:true});toast(`Yedek oluşturulamadı: ${error?.message||error}`)}}}if(json&&!json.dataset.appBackup){json.dataset.appBackup='1';json.onclick=async()=>{json.disabled=true;try{const data=await fullMetadata(),pending=data.offline_outbox?.length||0;R.download?.(`radyo-gunlugu-tam-yedek-${today()}.json`,JSON.stringify(data,null,2),'application/json');toast(`Tam veri yedeği hazırlandı: ${data.logs.length} günlük kaydı, ${data.session_attempts.length} dinleme denemesi${pending?` ve ${pending} bekleyen çevrimdışı kayıt`:''}. Ses dosyalarının kendisi JSON dosyasına eklenmez.`)}catch(error){R.reportError?.(error,'backup-metadata',{silent:true});toast(`Yedek oluşturulamadı: ${error?.message||error}`)}finally{json.disabled=false}}}}
R.backup={fullMetadata,fetchUserRows,fetchAudioManifest,fetchOfflineOutbox};R.events?.on?.('auth:changed',x=>{if(x?.authenticated)setTimeout(install,0)});R.events?.on?.('render:all',install);install();R.features?.register?.('backup',{ready:true,provider:'app-backup'});
})();
