(()=>{
const R=window.R;if(!R||R.__mapUI385)return;R.__mapUI385=true;const $=s=>document.querySelector(s),C=globalThis.RADIO_APP_CONFIG||{origin:{lat:38.151,lon:27.36}};let map=null,layer=null,resizeTimer=null,mapHost=null;
function validCoord(lat,lon){const a=Number(lat),b=Number(lon);return Number.isFinite(a)&&Number.isFinite(b)&&a>=-90&&a<=90&&b>=-180&&b<=180}
function origin(){const o=R.listeningOrigin?.()||C.origin||{},lat=Number(o.lat),lon=Number(o.lon);return validCoord(lat,lon)?{lat,lon}:{lat:38.151,lon:27.36}}
function points(){return(R.logs||[]).filter(x=>x.latitude!=null&&x.longitude!=null&&validCoord(x.latitude,x.longitude))}
function destroy(){try{map?.remove?.()}catch{}map=null;layer=null;mapHost=null;R.map=null;R.layer=null}
function render(){const rows=points(),count=$('#mapCount'),o=origin();if(count)count.textContent=`${rows.length} konumlu kayıt`;const host=$('#map');if(!host||typeof L==='undefined')return;if(map&&mapHost!==host)destroy();if(!map){mapHost=host;map=L.map(host).setView([o.lat,o.lon],9);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);layer=L.layerGroup().addTo(map);R.map=map;R.layer=layer}setTimeout(()=>map?.invalidateSize?.(),0);layer.clearLayers();for(const x of rows){const popup=`<b>${R.esc?.(x.station||'Radyo kaydı')||''}</b><br>${R.esc?.(x.date)||''} ${R.esc?.(String(x.time||'').slice(0,5))||''}<br>${R.esc?.(R.freq?.(x)||'')||''}<br>${R.esc?.(x.location||'')||''}`;L.marker([Number(x.latitude),Number(x.longitude)]).bindPopup(popup).addTo(layer)}if(rows.length){const bounds=L.latLngBounds(rows.map(x=>[Number(x.latitude),Number(x.longitude)]));map.fitBounds(bounds.pad(.2),{maxZoom:13})}else map.setView([o.lat,o.lon],9)}
function resizeMap(){clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{if(R.router?.current?.()==='map'&&map&&mapHost?.isConnected)map.invalidateSize?.({pan:false})},120)}
window.addEventListener('resize',resizeMap,{passive:true});
R.renderMap=render;R.mapUI={render,points,destroy,origin,validCoord,resizeMap};R.router?.register?.('map',{enter:()=>setTimeout(render,80)});R.events?.on?.('data:loaded',()=>{if(R.router?.current?.()==='map')setTimeout(render,0)});R.events?.on?.('user:settings',()=>{if(R.router?.current?.()==='map')setTimeout(render,0)});R.events?.on?.('auth:changed',x=>{if(!x?.authenticated)destroy()});R.features?.register?.('map-ui',{ready:true,provider:'app-map-ui'});
})();
