(()=>{
const R=window.R;if(!R||R.__qslUI385)return;R.__qslUI385=true;const $=s=>document.querySelector(s),esc=v=>R.esc?R.esc(v):String(v??'');
const LABELS={none:'Başlatılmadı',planned:'Gönderilecek',sent:'Gönderildi',received:'Yanıt geldi'};const contactResults=new Map();
function logById(id){return(R.logs||[]).find(x=>String(x.id)===String(id))}
function contactText(c){if(!c)return'<span>Doğrulanmış bir iletişim yolu henüz bulunamadı. Adres tahmini yapılmadı.</span>';const verified=c.verified_at?` · doğrulama ${esc(c.verified_at)}`:'',note=c.verification_note?`<span class="small" style="display:block;margin-top:5px;line-height:1.45">${esc(c.verification_note)}</span>`:'';if(c.email)return`<b>${esc(c.email)}</b><span>Önerilen e-posta${verified}</span>${note}`;return`<b>Resmî iletişim formu</b><span>Doğrudan doğrulanmış QSL e-postası yok${verified}</span>${note}`}
function contactActions(id,c){if(!c)return'';const open=c.email?'E-posta taslağını aç':'Resmî formu aç';return`<div class="row-actions" style="margin-top:7px"><button class="btn primary" type="button" data-qsl-action="open-contact" data-id="${esc(id)}">${open}</button><button class="btn ghost" type="button" data-qsl-action="save-contact" data-id="${esc(id)}">İletişimi kaydet</button>${c.source_url?`<button class="btn ghost" type="button" data-qsl-action="source-contact" data-id="${esc(id)}">Kaynağı aç</button>`:''}</div>`}
function renderContact(id,c){const box=$(`[data-qsl-contact-box="${CSS.escape(String(id))}"]`);if(!box)return;box.innerHTML=`<div>${contactText(c)}</div>${contactActions(id,c)}`}
function render(){const box=$('#qslList');if(!box)return;const rows=(R.logs||[]).filter(x=>x.qsl_status!=='none'||x.station||x.smart_station);box.innerHTML=rows.length?`<p class="hint" style="margin:0 0 10px">Rapor gövdesi yalnızca İngilizce üretilir; UTC tarih ve saat ana referanstır. Türkçe olduğu anlaşılan serbest notlar otomatik rapora karıştırılmaz. İletişim önerileri yalnızca kaynaklı dizinden gelir; e-posta tahmini yapılmaz.</p>`+rows.map(x=>`<div class="qsl-item" data-qslitem="${esc(x.id)}"><div class="record-top"><div><b>${esc(x.station||x.smart_station||'İsimsiz')}</b><div class="small">${esc(x.date)} · ${esc(R.freq?.(x)||'')}</div></div><span class="badge ${x.qsl_status==='received'?'ok':x.qsl_status==='sent'?'gold':''}">${esc(LABELS[x.qsl_status]||LABELS.none)}</span></div><div class="row-actions"><button class="btn ghost" type="button" data-qsl-action="copy" data-id="${esc(x.id)}">İngilizce raporu kopyala</button><button class="btn ghost" type="button" data-qsl-action="suggest-contact" data-id="${esc(x.id)}">İletişim öner</button><button class="btn ghost" type="button" data-qsl-action="planned" data-id="${esc(x.id)}">Planla</button><button class="btn ghost" type="button" data-qsl-action="sent" data-id="${esc(x.id)}">Gönderildi</button><button class="btn ghost" type="button" data-qsl-action="received" data-id="${esc(x.id)}">Yanıt geldi</button></div><div class="qsl-fieldset" style="margin-top:9px" data-qsl-contact-box="${esc(x.id)}"><div><span class="small">İstasyon için doğrulanmış e-posta veya resmî form aramak için “İletişim öner”e dokun.</span></div></div><details><summary>İngilizce rapor ve program ayrıntısı</summary><div class="qsl-report">${esc(R.qslService?.report?.(x)||'')}</div><label style="margin-top:10px">English programme details (optional)<textarea rows="3" data-qsl-details="${esc(x.id)}" placeholder="Example: Station identification, news bulletin, music, announcer name, time signal…">${esc(x.qsl_notes||'')}</textarea></label><p class="hint">Bu alanı İngilizce yaz. Türkçe serbest metin, rapor dilini bozmaması için reddedilir.</p><button class="btn ghost" type="button" data-qsl-action="save-details" data-id="${esc(x.id)}">İngilizce ayrıntıyı kaydet</button></details></div>`).join(''):'<p class="hint">Henüz kayıt yok.</p>';for(const [id,c] of contactResults)renderContact(id,c)}
async function copyReport(button,log){const text=R.qslService?.report?.(log)||'';try{await navigator.clipboard.writeText(text);const old=button.textContent;button.textContent='Kopyalandı';setTimeout(()=>{if(button.isConnected)button.textContent=old},1200)}catch{window.prompt('İngilizce QSL raporunu kopyala:',text)}}
async function suggest(button,log){const userId=R.me?.id;if(!userId)return;button.disabled=true;const target=$(`[data-qsl-contact-box="${CSS.escape(String(log.id))}"]`);if(target)target.innerHTML='<span class="small">Doğrulanmış iletişim yolu aranıyor…</span>';try{const c=await R.qslService?.suggestContact?.(log,{force:true})||null;if(R.me?.id!==userId)return;contactResults.set(String(log.id),c);renderContact(log.id,c)}catch(error){if(R.me?.id===userId&&target?.isConnected)target.innerHTML='<span class="small">İletişim dizini şu anda yüklenemedi.</span>';R.reportError?.(error,'qsl-contact-suggest',{silent:true})}finally{if(R.me?.id===userId&&button.isConnected)button.disabled=false}}
function openContact(log,c){if(!c)return;if(c.email){const draft=R.qslService?.emailDraft?.(log)||{subject:'Reception report',body:R.qslService?.report?.(log)||''};window.location.href=`mailto:${encodeURIComponent(c.email)}?subject=${encodeURIComponent(draft.subject)}&body=${encodeURIComponent(draft.body)}`;return}const url=R.qslService?.safeHttpUrl?.(c.contact_url);if(url)window.open(url,'_blank','noopener,noreferrer')}
function openSource(c){const url=R.qslService?.safeHttpUrl?.(c?.source_url);if(url)window.open(url,'_blank','noopener,noreferrer')}
async function act(button){const userId=R.me?.id;if(!userId)return;const id=button.dataset.id,action=button.dataset.qslAction,log=logById(id);if(!log)return;if(action==='copy')return copyReport(button,log);if(action==='suggest-contact')return suggest(button,log);const c=contactResults.get(String(id));if(action==='open-contact')return openContact(log,c);if(action==='source-contact')return openSource(c);if(button.dataset.busy==='1')return;button.dataset.busy='1';button.disabled=true;try{if(action==='save-contact'){if(!c)throw new Error('Önce doğrulanmış bir iletişim önerisi bul.');await R.qslService?.saveContact?.(id,c);if(R.me?.id!==userId)return;R.toast?.('QSL iletişim yolu kaydedildi.');return}if(action==='save-details'){const value=$(`[data-qsl-details="${CSS.escape(String(id))}"]`)?.value||'';await R.qslService?.setEnglishDetails?.(id,value);if(R.me?.id!==userId)return;R.toast?.('İngilizce program ayrıntısı kaydedildi.');render();return}await R.qslService?.setStatus?.(id,action);if(R.me?.id!==userId)return;R.toast?.('QSL durumu güncellendi.')}catch(error){if(R.me?.id===userId){R.toast?.(error?.message||'QSL işlemi tamamlanamadı.');R.reportError?.(error,'qsl-update',{silent:true})}}finally{if(R.me?.id===userId&&button.isConnected){delete button.dataset.busy;button.disabled=false}}}
function install(){const box=$('#qslList');if(!box||box.dataset.qslUi)return;box.dataset.qslUi='1';box.addEventListener('click',e=>{const b=e.target?.closest?.('[data-qsl-action]');if(b)act(b)})}
R.renderQsl=render;R.qslUI={render,install,contactResults};R.router?.register?.('qsl',{prepare:install,enter:()=>setTimeout(render,0)});R.events?.on?.('data:loaded',()=>{if(R.router?.current?.()==='qsl')render()});R.events?.on?.('auth:changed',x=>{contactResults.clear();if(!x?.authenticated&&R.router?.current?.()==='qsl')render()});install();R.features?.register?.('qsl-ui',{ready:true,provider:'app-qsl-ui'});
})();