(()=>{
const R=window.R;if(!R||R.__logUI386)return;R.__logUI386=true;const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],esc=v=>R.esc?R.esc(v):String(v??''),norm=v=>R.norm?R.norm(v):String(v??'').toLocaleLowerCase('tr-TR');let searchTimer=null;const VISIBLE_STEP=100;let visibleCount=VISIBLE_STEP;
function ownedLogs(){const userId=R.me?.id,rows=Array.isArray(R.logs)?R.logs:[];return userId?rows.filter(x=>!x?.user_id||x.user_id===userId):[]}
function signalValue(v){const n=Number(v);return Number.isInteger(n)&&n>=1&&n<=5?n:null}
function validCoords(x){const lat=Number(x?.latitude),lon=Number(x?.longitude);return Number.isFinite(lat)&&lat>=-90&&lat<=90&&Number.isFinite(lon)&&lon>=-180&&lon<=180}
function transcriptText(v){return typeof v==='string'?v.trim():''}
function confidenceValue(v){const n=Number(v);return Number.isFinite(n)&&n>=0&&n<=100?Math.round(n):null}
function ensureBandFilter(){const select=$('#filterBand');if(!select)return;for(const band of R.B||[])if(![...select.options].some(o=>o.value===band)){const o=document.createElement('option');o.value=band;o.textContent=band;select.appendChild(o)}}
function renderStats(){const logs=ownedLogs(),stations=new Set(logs.map(x=>norm(x.station)).filter(Boolean)).size,items=[['Toplam kayıt',logs.length],['Doğrulandı',logs.filter(x=>x.status==='confirmed').length],['Benzersiz istasyon',stations],['Sesli kayıt',logs.filter(x=>typeof x.audio_path==='string'&&x.audio_path.trim()).length],['Sinyal 5',logs.filter(x=>signalValue(x.signal_strength)===5).length],['QSL yanıtı',logs.filter(x=>x.qsl_status==='received').length],['Konumlu kayıt',logs.filter(validCoords).length],['Konuşma dökümlü',logs.filter(x=>transcriptText(x.transcript)).length]];const box=$('#stats');if(box)box.innerHTML=items.map(([label,value])=>`<div class="stat"><b>${value}</b><small>${esc(label)}</small></div>`).join('');return items}
function filtered(){const q=norm($('#search')?.value||''),band=$('#filterBand')?.value||'',date=$('#filterDate')?.value||'',status=$('#filterStatus')?.value||'';return ownedLogs().filter(x=>(!band||x.band===band)&&(!date||x.date===date)&&(!status||x.status===status)&&(!q||norm([x.station,x.smart_station,x.language,x.country,x.program,x.frequency,x.notes,transcriptText(x.transcript)].join(' ')).includes(q)))}
function recordHtml(x){const signal=signalValue(x.signal_strength),transcript=transcriptText(x.transcript),confidence=confidenceValue(x.smart_confidence);return `<article class="record-card" data-record-id="${esc(x.id)}"><div class="record-top" role="button" tabindex="0" aria-expanded="false" aria-label="${esc(x.station||x.smart_station||'İsimsiz kayıt')} ayrıntılarını aç veya kapat"><div><div class="record-title">${esc(x.station||x.smart_station||'İsimsiz kayıt')}</div><div class="record-meta">${esc(x.date)} ${esc(String(x.time||'').slice(0,5))} · ${esc(x.location||'')} · ${esc(R.freq?.(x)||'')}</div></div><div class="badges"><span class="badge">${esc(x.band)}</span><span class="badge ${x.status==='confirmed'?'ok':''}">${x.status==='confirmed'?'Doğrulandı':'Aday'}</span>${signal?`<span class="badge">Sinyal ${signal}/5</span>`:''}</div></div><div class="record-body">${esc(x.program||'')}${x.language?`<br><span class="small">${esc(x.language)}${x.country?' · '+esc(x.country):''}</span>`:''}</div>${x.smart_station?`<span class="badge gold">Öneri: ${esc(x.smart_station)}${confidence!==null?' %'+confidence:''}</span>`:''}${transcript?`<details><summary>Konuşma dökümü</summary><div class="record-body">${esc(transcript)}</div></details>`:''}<div class="record-actions"><button class="btn ghost" data-edit="${esc(x.id)}">Düzenle</button>${x.audio_path?`<button class="btn ghost" data-audio="${esc(x.id)}">🔊 Sesi aç</button>`:''}<button class="btn ghost" data-qsl="${esc(x.id)}">QSL raporu</button><button class="btn ghost danger" data-delete="${esc(x.id)}">Sil</button></div></article>`}
function setExpanded(card,expanded){if(!card)return false;card.classList.toggle('v38-expanded',!!expanded);card.querySelector('.record-top')?.setAttribute('aria-expanded',expanded?'true':'false');return !!expanded}
function toggleRecord(card){return setExpanded(card,!card?.classList.contains('v38-expanded'))}
function renderRecords({resetLimit=false}={}){const box=$('#records');if(!box)return[];if(resetLimit)visibleCount=VISIBLE_STEP;const rows=filtered(),shown=rows.slice(0,visibleCount),remaining=Math.max(0,rows.length-shown.length);box.innerHTML=rows.length?shown.map(recordHtml).join('')+(remaining?`<div class="v38-log-more"><button class="btn ghost" type="button" data-log-more>Daha fazla göster <span>(${remaining.toLocaleString('tr-TR')} kayıt)</span></button></div>`:''):'<p class="hint">Filtrelerle eşleşen kayıt yok.</p>';decorate();return rows}
function ensureBar(){const tab=$('#tab-log'),records=tab?.querySelector('.records-card');if(!tab||!records)return;const filters=records.querySelector('.filters');if(filters&&!filters.id)filters.id='logFilters';if($('#v38Logbar'))return;const b=document.createElement('div');b.id='v38Logbar';b.className='v38-logbar';b.innerHTML='<div><h2>Günlük</h2><p>Ayrıntıları açmak için kayıt kartını seç veya Enter tuşuna bas.</p></div><div class="v38-logactions"><button class="btn primary" data-detail-new>Yeni kayıt</button><button class="btn ghost" data-log-filters aria-expanded="false" aria-controls="logFilters">Filtre</button></div>';records.parentElement?.insertBefore(b,records)}
function decorate(){ensureBar();$$('#records .record-card').forEach(c=>setExpanded(c,false));const filters=$('#tab-log .records-card');const toggle=$('[data-log-filters]');if(toggle)toggle.setAttribute('aria-expanded',filters?.classList.contains('v38-filters-open')?'true':'false')}
async function play(id){const log=ownedLogs().find(x=>String(x.id)===String(id));if(!log?.audio_path)return;let popup=null;try{popup=window.open('about:blank','_blank');const url=await R.records?.signedAudioUrl?.(log.audio_path,600);if(!url)throw new Error('Ses bağlantısı oluşturulamadı.');if(popup)popup.location=url;else{const a=document.createElement('a');a.href=url;a.target='_blank';a.rel='noopener';a.click()}}catch(error){try{popup?.close()}catch{}R.toast?.(error?.message||String(error));R.reportError?.(error,'log-audio',{silent:true})}}
async function remove(id){const log=ownedLogs().find(x=>String(x.id)===String(id));if(!log||!confirm('Bu kaydı silmek istiyor musun?'))return;try{await R.records?.remove?.(log.id);await R.load?.();R.toast?.('Kayıt silindi.')}catch(error){R.toast?.(error?.message||String(error));R.reportError?.(error,'log-delete',{silent:true})}}
function resetVisible(){visibleCount=VISIBLE_STEP;return renderRecords()}
function installFilters(){ensureBandFilter();for(const id of ['search','filterBand','filterDate','filterStatus']){const el=$('#'+id);if(!el||el.dataset.logFilter)return;el.dataset.logFilter='1';if(id==='search')el.addEventListener('input',()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>{if(R.router?.current?.()==='log')resetVisible()},140)});else el.addEventListener('change',()=>{if(R.router?.current?.()==='log')resetVisible()})}}
document.addEventListener('click',async e=>{const target=e.target?.closest?e.target:null;if(!target)return;if(target.closest('[data-detail-new]')){R.reset?.();$('#tab-log')?.classList.add('v38-form-open');return}const filterButton=target.closest('[data-log-filters]');if(filterButton){const card=$('#tab-log .records-card'),open=!card?.classList.contains('v38-filters-open');card?.classList.toggle('v38-filters-open',open);filterButton.setAttribute('aria-expanded',open?'true':'false');if(open)setTimeout(()=>$('#search')?.focus(),0);return}if(target.closest('[data-log-more]')){visibleCount+=VISIBLE_STEP;return renderRecords()}const edit=target.closest('[data-edit]');if(edit){e.preventDefault();return R.edit?.(edit.dataset.edit)}const del=target.closest('[data-delete]');if(del){e.preventDefault();return remove(del.dataset.delete)}const audio=target.closest('[data-audio]');if(audio){e.preventDefault();return play(audio.dataset.audio)}const qsl=target.closest('[data-qsl]');if(qsl){e.preventDefault();R.router?.go?.('qsl',{source:'log-qsl',historyMode:'push'});return setTimeout(()=>document.querySelector(`[data-qslitem="${CSS.escape(String(qsl.dataset.qsl))}"]`)?.scrollIntoView({behavior:'smooth'}),100)}const top=target.closest('#records .record-card .record-top');if(top&&!target.closest('button,a,input,select'))toggleRecord(top.closest('.record-card'))},true);
document.addEventListener('keydown',e=>{const top=e.target.closest?.('#records .record-card .record-top');if(!top||!['Enter',' '].includes(e.key))return;e.preventDefault();toggleRecord(top.closest('.record-card'))},true);
function render({resetLimit=false}={}){installFilters();renderStats();renderRecords({resetLimit});decorate()}
R.events?.on?.('route:changed',x=>{if(x?.to==='log')render({resetLimit:true})});R.events?.on?.('render:all',()=>{if(R.router?.current?.()==='log')render()});R.events?.on?.('auth:changed',x=>{visibleCount=VISIBLE_STEP;clearTimeout(searchTimer);searchTimer=null;if(x?.authenticated&&R.router?.current?.()==='log')setTimeout(()=>render({resetLimit:true}),0)});
R.renderStats=renderStats;R.filtered=filtered;R.renderRecords=renderRecords;R.play=play;R.logUI={render,renderStats,renderRecords,filtered,decorate,ensureBar,play,remove,setExpanded,toggleRecord,ownedLogs,signalValue,validCoords,transcriptText,confidenceValue,visibleStep:VISIBLE_STEP};installFilters();setTimeout(()=>{if(R.router?.current?.()==='log')render({resetLimit:true})},100);R.features?.register?.('log-ui',{ready:true,provider:'app-log-ui'});
})();
