(()=>{
const R=window.R;if(!R||R.__menuUI381)return;R.__menuUI381=true;const $=s=>document.querySelector(s),esc=v=>R.esc?R.esc(v):String(v??'');
function close(){$('#v38Overlay')?.remove();$('#v38Sheet')?.remove()}
function sheet(title,body){close();const o=document.createElement('div');o.id='v38Overlay';o.className='v38-overlay';o.onclick=close;const s=document.createElement('div');s.id='v38Sheet';s.className='v38-sheet';s.innerHTML=`<div class="v38-sheethead"><h2>${esc(title)}</h2><button class="v38-close">×</button></div>${body}`;document.body.append(o,s);s.querySelector('.v38-close').onclick=close;R.events?.emit?.('menu:opened',{sheet:s,title});return s}
function row(a,b,action){return `<button class="v38-menu-row" data-action="${action}"><span style="display:block;color:inherit;font-size:inherit"><b>${esc(a)}</b><small>${esc(b)}</small></span><span>›</span></button>`}
function open(){return sheet('Menü',`<details class="v38-menu-group" open><summary>Koleksiyon</summary><div class="v38-menu-list">${row('Radyo Hafızası','İstasyon, frekans ve ülke profilleri','route:memory')}${row('Radyo Atlası','Ülke, yön ve dinleme geçmişi','route:atlas')}${row('QSL','Reception report ve cevaplar','route:qsl')}${row('Başarılar','Rozet ve koleksiyon ilerlemesi','achievements')}${row('Favoriler','Kaydettiğin yayın hedefleri','favorites')}</div></details><details class="v38-menu-group"><summary>Araçlar</summary><div class="v38-menu-list">${row('Yayılım Asistanı','Gray-line, uzay havası ve kişisel bant tahmini','route:propagation')}${row('AI Ses Analizi','Ses, dil ve istasyon adayları','route:ai')}${row('Yayın Rehberi','Frekans ve yayın pencereleri','route:guide')}${row('Akıllı Dinleme','Oturumlar, gizemler ve kalibrasyon','route:smart')}${row('Ses Kaydı','Radyo sesini kaydet ve yazıya çevir','route:audio')}${row('Konum Haritası','GPS eklenen dinleme kayıtları','route:map')}</div></details><details class="v38-menu-group"><summary>Geçmiş</summary><div class="v38-menu-list">${row('Günlük','Tüm dinleme kayıtların','route:log')}${row('Takvim','Dinleme günlerini gör','route:calendar')}${row('İstatistikler','Bant, dil ve çekim analizi','route:analysis')}</div></details><details class="v38-menu-group"><summary>Ayarlar</summary><div class="v38-menu-list">${row('Hatırlatıcılar','Yayın saatlerini takip et','reminders')}${row('Görünüm','Açık / gece modu','theme')}${row('Senkronizasyon','Offline kuyruğu buluta gönder','sync')}${row('Sistem Durumu','Router, veri ve PWA tanıları','diagnostics')}${row('Uygulamayı kur','PWA kurulumunu başlat','install')}</div></details><div class="v38-menu-footer"><button class="btn ghost" data-action="logout">Çıkış</button></div>`)}
async function favorites(){let a=R.favorites||[];if(!a.length&&R.me){const q=await R.S.from('radio_favorites').select('*').eq('user_id',R.me.id).order('created_at',{ascending:false});if(!q.error){a=q.data||[];R.favorites=a}}return sheet('Favoriler',`<div class="v38-mini-list">${a.length?a.map(x=>`<div class="v38-mini"><b>${esc(x.station||'İsimsiz yayın')}</b><small>${esc(x.band||'')} · ${Number(x.frequency).toLocaleString('tr-TR')} ${esc(x.unit||'')} ${x.note?'· '+esc(x.note):''}</small></div>`).join(''):'<div class="v38-empty">Henüz favori yayın yok.</div>'}</div>`)}
async function reminders(){let a=[];if(R.me){const q=await R.S.from('radio_reminders').select('*').eq('user_id',R.me.id).order('reminder_time');if(!q.error){a=q.data||[];R.reminders=a}}return sheet('Hatırlatıcılar',`<div class="v38-mini-list">${a.length?a.map(x=>`<div class="v38-mini" style="display:flex;justify-content:space-between;gap:8px;align-items:center"><div><b>${esc(x.station||'Yayın')}</b><small>${String(x.reminder_time||'').slice(0,5)} · ${esc(x.band||'')} ${Number(x.frequency).toLocaleString('tr-TR')} ${esc(x.unit||'')}</small></div><button class="v38-toggle ${x.enabled?'on':''}" data-reminder="${x.id}" data-enabled="${x.enabled?'1':'0'}">${x.enabled?'Açık':'Kapalı'}</button></div>`).join(''):'<div class="v38-empty">Henüz hatırlatıcı yok.</div>'}</div>`)}
async function action(a){if(a?.startsWith('route:')){close();return R.router?.go?.(a.slice(6),{source:'menu',historyMode:'push'})}if(a==='achievements'){close();return R.openAchievements?.()}if(a==='favorites')return favorites();if(a==='reminders')return reminders();if(a==='theme'){document.body.classList.toggle('night-mode');document.documentElement.classList.toggle('night');localStorage.setItem('radio-night',document.body.classList.contains('night-mode')?'1':'0');return}if(a==='sync'){await R.syncOutbox?.();return R.toast?.('Senkronizasyon kontrol edildi.')}if(a==='diagnostics'){close();return R.openDiagnostics?.()}if(a==='install'){close();return R.installPWA?.()}if(a==='logout'){close();$('#logoutBtn')?.click()}}
document.addEventListener('click',async e=>{if(e.target.closest('[data-menu]'))return open();const a=e.target.closest('#v38Sheet [data-action]');if(a)return action(a.dataset.action);const b=e.target.closest('#v38Sheet [data-reminder]');if(b){const enabled=b.dataset.enabled!=='1',q=await R.S.from('radio_reminders').update({enabled}).eq('id',b.dataset.reminder).eq('user_id',R.me.id);if(!q.error){b.dataset.enabled=enabled?'1':'0';b.textContent=enabled?'Açık':'Kapalı';b.classList.toggle('on',enabled)}return}},true);
R.events?.on?.('auth:changed',x=>{if(!x?.authenticated)close()});R.menuUI={open,close,sheet,favorites,reminders,action};R.features?.register?.('menu-ui',{ready:true,provider:'app-menu-ui'});
})();