(()=>{
const R=window.R;if(!R||R.__qslUI386)return;R.__qslUI386=true;const $=s=>document.querySelector(s),esc=v=>R.esc?R.esc(v):String(v??'');
const LABELS={none:'Başlatılmadı',planned:'Gönderilecek',sent:'Gönderildi',received:'Yanıt geldi'};const contactResults=new Map(),mutationFlights=new Map();
function ownedLogs(){const userId=R.me?.id||null;if(!userId)return[];return(R.logs||[]).filter(x=>x?.user_id==null||x.user_id===userId)}
function logById(id){return ownedLogs().find(x=>String(x.id)===String(id))||null}
function contactText(c){if(!c)return'<span>Doğrulanmış bir iletişim yolu henüz bulunamadı. Adres tahmini yapılmadı.</span>';if(c.saved){if(c.email)return`<b>${esc(c.email)}</b><span>Kaydedilmiş e-posta · güncelliği doğrulanmamış olabilir</span>`;return`<b>Kaydedilmiş iletişim formu</b><span>Daha önce kaydedilmiş bağlantı · güncelliği doğrulanmamış olabilir</span>`}const verified=c.verified_at?` · doğrulama ${esc(c.verified_at)}`:'',note=c.verification_note?`<span class="small app-qsl-verification-note">${esc(c.verification_note)}</span>`:'';if(c.email)return`<b>${esc(c.email)}</b><span>Doğrulanmış e-posta${verified}</span>${note}`;return`<b>Resmî iletişim formu</b><span>Doğrudan doğrulanmış bir QSL e-posta adresi yok${verified}</span>${note}`}
function contactActions(id,c){if(!c)return'';const open=c.email?'E-posta taslağını aç':'Resmî formu aç';return`<div class="row-actions app-qsl-contact-actions"><button class="btn primary" type="button" data-qsl-action="open-contact" data-id="${esc(id)}">${open}</button><button class="btn ghost" type="button" data-qsl-action="save-contact" data-id="${esc(id)}">İletişimi kaydet</button>${c.source_url?`<button class="btn ghost" type="button" data-qsl-action="source-contact" data-id="${esc(id)}">Kaynak</button>`:''}</div>`}
function renderContact(id,c){const box=$(`[data-qsl-contact-box="${CSS.escape(String(id))}"]`);if(!box)return;box.innerHTML=`<div>${contactText(c)}</div>${contactActions(id,c)}`}
function progress(id,status){const steps=[['planned','Planlandı'],['sent','Gönderildi'],['received','Yanıt geldi']];return`<div class="app-qsl-progress" role="group" aria-label="QSL süreci">${steps.map(([value,label],index)=>{const rank={none:-1,planned:0,sent:1,received:2}[status]??-1,active=rank>=index,current=status===value;return`<button type="button" class="app-qsl-step ${active?'is-complete':''} ${current?'is-current':''}" data-qsl-action="${value}" data-id="${esc(id)}" aria-pressed="${current?'true':'false'}"><span>${index+1}</span><b>${label}</b></button>`}).join('')}</div>`}
function activeItem(x){return`<article class="qsl-item" data-qslitem="${esc(x.id)}"><div class="record-top"><div><b>${esc(x.station||x.smart_station||'Adı belirtilmemiş yayın')}</b><div class="small">${esc(x.date)} · ${esc(R.freq?.(x)||'')}</div></div><span class="badge ${x.qsl_status==='received'?'ok':x.qsl_status==='sent'?'gold':''}">${esc(LABELS[x.qsl_status]||LABELS.none)}</span></div>${progress(x.id,x.qsl_status)}<div class="row-actions app-qsl-primary-actions"><button class="btn primary" type="button" data-qsl-action="copy" data-id="${esc(x.id)}">İngilizce raporu kopyala</button><button class="btn ghost" type="button" data-qsl-action="suggest-contact" data-id="${esc(x.id)}">İletişim bilgisi bul</button></div><div class="qsl-fieldset app-qsl-contact-box" data-qsl-contact-box="${esc(x.id)}"><div><span class="small">Doğrulanmış e-posta veya resmî iletişim formu için “İletişim bilgisi bul”u kullan.</span></div></div><details class="app-qsl-details"><summary>Rapor ve program ayrıntıları</summary><div class="qsl-report">${esc(R.qslService?.report?.(x)||'')}</div><label>Program ayrıntıları (İngilizce, isteğe bağlı)<textarea rows="3" data-qsl-details="${esc(x.id)}" placeholder="Example: Station identification, news bulletin, music, announcer name, time signal…">${esc(x.qsl_notes||'')}</textarea></label><p class="hint">Bu alan İngilizce olmalıdır. Türkçe serbest notlar QSL raporuna otomatik eklenmez.</p><button class="btn ghost" type="button" data-qsl-action="save-details" data-id="${esc(x.id)}">İngilizce ayrıntıları kaydet</button></details></article>`}
function backlogItem(x){return`<div class="app-qsl-backlog-row" data-qslitem="${esc(x.id)}"><div><b>${esc(x.station||x.smart_station||'Adı belirtilmemiş yayın')}</b><span>${esc(x.date)} · ${esc(R.freq?.(x)||'')}</span></div><button class="btn ghost" type="button" data-qsl-action="planned" data-id="${esc(x.id)}">QSL sürecini başlat</button></div>`}
function render(){const box=$('#qslList');if(!box)return;const all=ownedLogs().filter(x=>x.station||x.smart_station),active=all.filter(x=>x.qsl_status&&x.qsl_status!=='none'),backlog=all.filter(x=>!x.qsl_status||x.qsl_status==='none');box.innerHTML=`<p class="hint app-qsl-intro">QSL raporu İngilizce hazırlanır; tarih ve saatte UTC esas alınır. İletişim bilgileri yalnızca doğrulanmış kaynaklardan önerilir ve e-posta adresi tahmin edilmez.</p>${active.length?`<div class="app-qsl-active">${active.map(activeItem).join('')}</div>`:'<div class="app-qsl-empty"><b>Etkin QSL süreci yok.</b><p>Bir dinleme kaydında QSL sürecini başlattığında ilerleme burada görünür.</p></div>'}${backlog.length?`<details class="app-qsl-backlog"><summary>QSL başlatılmamış kayıtlar <span>${backlog.length.toLocaleString('tr-TR')}</span></summary><div>${backlog.map(backlogItem).join('')}</div></details>`:''}`;for(const [id,c] of contactResults)if(logById(id))renderContact(id,c)}
async function copyReport(button,log){const text=R.qslService?.report?.(log)||'';try{await navigator.clipboard.writeText(text);const old=button.textContent;button.textContent='Kopyalandı';setTimeout(()=>{if(button.isConnected)button.textContent=old},1200)}catch{window.prompt('İngilizce QSL raporunu kopyala:',text)}}
async function suggest(button,log){const userId=R.me?.id;if(!userId)return;button.disabled=true;const target=$(`[data-qsl-contact-box="${CSS.escape(String(log.id))}"]`);if(target)target.innerHTML='<span class="small">Doğrulanmış iletişim bilgisi aranıyor…</span>';try{const c=await R.qslService?.suggestContact?.(log,{force:true})||null;if(R.me?.id!==userId)return;contactResults.set(String(log.id),c);renderContact(log.id,c)}catch(error){if(R.me?.id===userId&&target?.isConnected)target.innerHTML='<span class="small">İletişim dizini şu anda yüklenemedi.</span>';R.reportError?.(error,'qsl-contact-suggest',{silent:true})}finally{if(R.me?.id===userId&&button.isConnected)button.disabled=false}}
function openContact(log,c){if(!c)return;if(c.email){const draft=R.qslService?.emailDraft?.(log)||{subject:'Reception report',body:R.qslService?.report?.(log)||''};window.location.href=`mailto:${encodeURIComponent(c.email)}?subject=${encodeURIComponent(draft.subject)}&body=${encodeURIComponent(draft.body)}`;return}const url=R.qslService?.safeHttpUrl?.(c.contact_url);if(url)window.open(url,'_blank','noopener,noreferrer')}
function openSource(c){const url=R.qslService?.safeHttpUrl?.(c?.source_url);if(url)window.open(url,'_blank','noopener,noreferrer')}
async function act(button){const userId=R.me?.id;if(!userId)return;const id=button.dataset.id,action=button.dataset.qslAction,log=logById(id);if(!log)return;if(action==='copy')return copyReport(button,log);if(action==='suggest-contact')return suggest(button,log);const c=contactResults.get(String(id));if(action==='open-contact')return openContact(log,c);if(action==='source-contact')return openSource(c);const key=`${userId}|${id}`;if(mutationFlights.has(key))return mutationFlights.get(key);const item=button.closest('[data-qslitem]'),buttons=[...(item?.querySelectorAll?.('[data-qsl-action]')||[button])];buttons.forEach(x=>x.disabled=true);const flight=(async()=>{try{if(action==='save-contact'){if(!c)throw new Error('Önce doğrulanmış bir iletişim bilgisi bul.');await R.qslService?.saveContact?.(id,c);if(R.me?.id!==userId)return;R.toast?.('QSL iletişim bilgisi kaydedildi.');return}if(action==='save-details'){const value=$(`[data-qsl-details="${CSS.escape(String(id))}"]`)?.value||'';await R.qslService?.setEnglishDetails?.(id,value);if(R.me?.id!==userId)return;R.toast?.('İngilizce program ayrıntıları kaydedildi.');render();return}await R.qslService?.setStatus?.(id,action);if(R.me?.id!==userId)return;R.toast?.('QSL durumu güncellendi.');render()}catch(error){if(R.me?.id===userId){R.toast?.(error?.message||'QSL işlemi tamamlanamadı.');R.reportError?.(error,'qsl-update',{silent:true})}}finally{if(R.me?.id===userId)for(const x of buttons)if(x.isConnected)x.disabled=false}})().finally(()=>mutationFlights.delete(key));mutationFlights.set(key,flight);return flight}
function install(){const box=$('#qslList');if(!box||box.dataset.qslUi)return;box.dataset.qslUi='1';box.addEventListener('click',e=>{const b=e.target?.closest?.('[data-qsl-action]');if(b)act(b)})}
R.renderQsl=render;R.qslUI={render,install,ownedLogs,contactResults,mutationFlights,contactText,progress};R.router?.register?.('qsl',{prepare:install,enter:()=>setTimeout(render,0)});R.events?.on?.('data:loaded',()=>{if(R.router?.current?.()==='qsl')render()});R.events?.on?.('auth:changed',x=>{contactResults.clear();if(R.router?.current?.()==='qsl')setTimeout(render,0)});install();R.features?.register?.('qsl-ui',{ready:true,provider:'app-qsl-ui'});
})();