(()=>{
const R=window.R;if(!R||R.__nowUI386)return;R.__nowUI386=true;
const $=s=>document.querySelector(s),C=globalThis.RADIO_APP_CONFIG||{timezone:'Europe/Istanbul',origin:{name:'Bozköy, Torbalı, İzmir'}},TZ=C.timezone||'Europe/Istanbul',esc=v=>R.esc?R.esc(v):String(v??'');
const fallbackLabelFmt=new Intl.DateTimeFormat('tr-TR',{timeZone:TZ,weekday:'long',day:'numeric',month:'long',hour:'2-digit',minute:'2-digit',hourCycle:'h23'});
const MODES=new Set(['ALL','SW','MW','FM']);let visibleLimit=30,minuteTimer=null,renderTimer=null,mwLoadRequested=false,mwLoadAttempted=false;
function ensureTab(){let t=$('#tab-now');if(!t){t=document.createElement('section');t.id='tab-now';t.className='tab-view hidden';const app=$('#appView'),log=$('#tab-log');app?.insertBefore(t,log||app.firstChild)}return t}
function ensure(){const t=ensureTab();let x=$('#v38Now');if(!x){x=document.createElement('div');x.id='v38Now';x.className='v38-now';t.appendChild(x)}return x}
function mode(){const v=R.uiState?.nowMode||R.nowMode||'ALL';return MODES.has(v)?v:'ALL'}
function labelNow(){try{const value=R.clock?.format?.(new Date(),{weekday:'long',day:'numeric',month:'long',hour:'2-digit',minute:'2-digit',hourCycle:'h23'});if(value)return value}catch{}return fallbackLabelFmt.format(new Date())}
function originName(){return R.listeningOrigin?.()?.name||C.origin?.name||'Bozköy, Torbalı, İzmir'}
function band(e){return e?._radioConsole?'MW':e?.mode==='SW'?(e.band||'SW'):(e?.mode||e?.band||'')}
function unit(e){return e?._radioConsole?'kHz':e?.unit||((e?.mode||e?.band)==='FM'?'MHz':'kHz')}
function validCandidate(e){const f=Number(e?.frequency),id=e?._radioConsole?e?.schedule_id:e?.id;if(!e||id===null||id===undefined||String(id).trim()===''||!Number.isFinite(f)||f<=0)return false;if(!e._radioConsole&&R.currentPrograms?.receiverCompatible?.(e)===false)return false;return true}
function legacyCandidates(m=mode()){try{if(typeof R.radioNowCandidates==='function'){const rows=R.radioNowCandidates(m);return(Array.isArray(rows)?rows:[]).filter(validCandidate)}const result=R.currentSuggestions?.()||[];return(m==='ALL'?result:result.filter(x=>x.mode===m)).filter(validCandidate)}catch(error){R.reportError?.(error,'now-candidates',{silent:true});return[]}}
function mwCandidates(){return(R.radioConsole?.rows?.()||[]).filter(validCandidate)}
function dedupe(rows){const map=new Map();for(const x of rows){const id=x?._radioConsole?`mw:${x.schedule_id}`:`g:${x.id}`;if(!map.has(id))map.set(id,x)}return[...map.values()]}
function candidates(m=mode()){const mw=mwCandidates();if(m==='MW')return mw.length?mw:legacyCandidates('MW');if(m==='ALL'){const legacy=legacyCandidates('ALL').filter(x=>x.mode!=='MW'&&x.band!=='MW');return dedupe([...mw,...legacy])}return legacyCandidates(m)}
function fmtFreq(e){const n=Number(e?.frequency);return `${Number.isFinite(n)&&n>0?n.toLocaleString('tr-TR',{maximumFractionDigits:3}):'—'} ${unit(e)}`}
function station(e){return String(e?.canonical_name||e?.station||'Yayın adayı').trim()||'Yayın adayı'}
function lang(e){return String(e?.language_content||e?.language||'').split(/[;/,]/)[0].trim()}
function cleanSource(value){return String(value??'').replace(/[\u0000-\u001f\u007f-\u009f]+/g,' ').replace(/\s+/g,' ').trim()}
function sourceText(e){const value=cleanSource(e?.source_doc||e?.source||e?.schedule_source);return value?`Kaynak: ${value}`:''}
function score(e){const raw=Number(e?._score??e?._s?.score??e?.probability_score??50),n=Number.isFinite(raw)?raw:50;return Math.max(1,Math.min(99,Math.round(n)))}
function displayScore(e){if(e?._radioConsole){const n=Number(e.score);return Number.isFinite(n)?Math.max(0,Math.min(100,Math.round(n))):null}const raw=e?._score??e?._s?.score??e?.probability_score;if(raw===null||raw===undefined||raw==='')return null;const n=Number(raw);return Number.isFinite(n)?Math.max(1,Math.min(99,Math.round(n))):null}
function quality(n,max=100){if(!Number.isFinite(n))return'Puan yok';const p=n/max;return p>=.75?'Güçlü aday':p>=.55?'Denenebilir':p>=.4?'Orta':'Zayıf aday'}
function windowText(e){return e?._radioConsole?(R.radioConsole?.guideMeta?.(e)?.time||''):R.guideService?.currentWindowText?.(e,R.clock?.today?.(),R.clock?.time?.())||e?.time_text||''}
function guideReady(){return Array.isArray(R.guideEntries)&&R.guideEntries.length>0}
function className(e){return e?._radioConsole?R.radioConsole?.classKey?.(e.reception_class)||'unknown':'unknown'}
function geoText(e){if(!e?._radioConsole)return'';if(Number.isFinite(Number(e.distance_km)))return`${Math.round(Number(e.distance_km)).toLocaleString('tr-TR')} km${e.bearing_direction?` · ${e.bearing_direction}`:''}`;if(e.transmitter_site_name)return'Saha biliniyor · koordinat doğrulanmadı';return'Verici konumu belirsiz'}
function reasonParts(e){if(e?._radioConsole)return R.radioConsole?.reasons?.(e)||[];const sc=e?._s||e?._guideScore||R.guideService?.scoreEntry?.(e)||{why:[]};return(sc.why||[]).map(String)}
function signed(n){const v=Number(n);return Number.isFinite(v)&&v!==0?`${v>0?'+':''}${v}`:''}
function signedLocale(n){const v=Number(n);if(!Number.isFinite(v))return'';const text=v.toLocaleString('tr-TR',{maximumFractionDigits:1});return`${v>0?'+':''}${text}`}
function contributionTone(n){const v=Number(n);return!Number.isFinite(v)||v===0?'muted':v>0?'positive':'negative'}
function chipColor(tone){return tone==='positive'?'var(--radio-green)':tone==='negative'?'var(--radio-danger)':tone==='day'?'var(--radio-amber)':tone==='night'||tone==='distance'?'var(--radio-blue)':'var(--radio-muted)'}
function mwReasonChips(e){const intel=R.radioConsole?.intelligence?.(e)||{},p=intel.propagation||{},solar=Number(p.solar_elevation),distance=Number(e?.distance_km),tb=Number(intel.target?.bonus),pa=Number(intel.personal?.adjustment)||0,targetKnown=Boolean(intel.target?.text);return[
  {label:p.period==='night'?'Gece':p.period==='day'?'Gündüz':'Yayılım',bonus:Number.isFinite(solar)?`${signedLocale(solar)}°`:'•',tone:p.period==='night'?'night':p.period==='day'?'day':'muted'},
  {label:'Mesafe',bonus:Number.isFinite(distance)?`${Math.round(distance).toLocaleString('tr-TR')} km`:e?.transmitter_site_name?'koordinat yok':'belirsiz',tone:Number.isFinite(distance)?'distance':'muted'},
  {label:'Hedef',bonus:targetKnown?(signed(tb)||'nötr'):'bilinmiyor',tone:targetKnown?contributionTone(tb):'muted'},
  {label:'Geçmişim',bonus:signed(pa)||'etkisiz',tone:contributionTone(pa)}
]}
function whyParts(e){if(!e?._radioConsole)return reasonParts(e).slice(0,4);const intel=R.radioConsole?.intelligence?.(e)||{},geo=geoText(e);return[intel.activity?.text,geo?`Mesafe / konum: ${geo}`:'',intel.target?.text,intel.personal?.text,intel.propagation?.text].filter(Boolean).slice(0,5)}
function scale(frequency){const s=R.radioConsole?.bandScale?.(frequency)||{pct:50,ticks:[531,603,720,873,1188,1350,1602]};return `<div class="radio-dial"><div class="radio-dial-head"><b>MW bandı</b><span>kHz</span></div><div class="radio-dial-track"><i style="left:${s.pct}%"></i></div><div class="radio-dial-labels">${s.ticks.map(x=>`<span class="${Number(x)===Number(frequency)?'active':''}">${x}</span>`).join('')}</div></div>`}
function actions(e){if(e?._radioConsole){const match=R.radioConsole?.guideMatch?.(e),listen=match?`<button type="button" class="btn primary" data-listen="${esc(match.id)}">Dinlemeye başla</button>`:'',prefill=match?`<button type="button" class="btn ghost" data-prefill="${esc(match.id)}">Kayıt formuna aktar</button>`:'';return `<button type="button" class="btn ghost" data-station-detail="${esc(e.schedule_id)}">Detay</button>${listen}${prefill}`}return `<button type="button" class="btn primary" data-listen="${esc(e.id)}">Dinle</button><button type="button" class="btn ghost" data-prefill="${esc(e.id)}">Kayıt formuna aktar</button>`}
function featured(e){if(!e)return'';const s=displayScore(e),klass=className(e),src=sourceText(e),chips=e?._radioConsole?mwReasonChips(e):[];return `<article class="radio-hero"><div class="radio-hero-main"><div class="radio-frequency">${esc(fmtFreq(e))}</div><h3>${esc(station(e))}</h3><p class="site-line">${esc(e?._radioConsole?[e.transmitter_site_name,e.country_name].filter(Boolean).join(' · '):[band(e),lang(e)||e.country,windowText(e)].filter(Boolean).join(' · '))}</p><span class="radio-live ${e?._radioConsole&&e.active_now?'on':''}">${e?._radioConsole?(e.active_now?'● Şu an yayında':'○ Şu an çizelgede aktif değil'):(windowText(e)?`● ${esc(windowText(e))}`:'Yayın adayı')}</span>${e?._radioConsole?`<p class="site-line">${esc(geoText(e))}</p>`:''}${src?`<p class="site-line radio-source">${esc(src)}</p>`:''}</div><div class="radio-hero-score">${e?._radioConsole?`<span class="radio-class ${klass}">${esc(e.reception_class)}</span>`:''}<div class="radio-score-box"${s===null?' data-score-unknown="true"':''}><small>${esc(quality(s,e?._radioConsole?100:99))}</small><b>${s===null?'—':s}<em>/${e?._radioConsole?'100':'99'}</em></b></div></div>${e?._radioConsole?`<div class="radio-reasons">${chips.map(x=>`<div class="radio-reason-chip tone-${esc(x.tone)}"><span>${esc(x.label)}</span><b style="color:${chipColor(x.tone)}">${esc(x.bonus)}</b></div>`).join('')}</div>`:''}<div class="radio-hero-actions">${actions(e)}</div></article>`}
function candidateCard(e){const s=displayScore(e),klass=className(e),src=sourceText(e),isMw=!!e?._radioConsole,geo=isMw?geoText(e):[band(e),lang(e)||e.country,windowText(e)].filter(Boolean).join(' · '),site=isMw?[e.transmitter_site_name,e.country_name].filter(Boolean).join(' · '):geo,max=isMw?100:99,q=quality(s,max);return `<button type="button" class="radio-candidate-card" ${isMw?`data-station-detail="${esc(e.schedule_id)}"`:`data-listen="${esc(e.id)}"`}><div class="radio-candidate-top"><div class="freq">${Number(e.frequency).toLocaleString('tr-TR',{maximumFractionDigits:3})} <small>${esc(unit(e))}</small></div><span class="radio-candidate-score"${s===null?' data-score-unknown="true"':''}>${s===null?'—':s}<small>/${max}</small></span></div><b class="radio-candidate-name">${esc(station(e))}</b><p class="radio-candidate-site">${esc(site||'Verici veya yayın konumu belirtilmemiş')}</p><div class="radio-candidate-meta">${isMw?`<span class="radio-candidate-status ${e.active_now?'on':''}">${e.active_now?'● yayında':'○ aktif değil'}</span>`:''}${geo?`<span>${esc(geo)}</span>`:''}</div>${src?`<p class="radio-source">${esc(src)}</p>`:''}<div class="radio-candidate-footer">${isMw?`<span class="radio-class ${klass}">${esc(e.reception_class)}</span>`:`<span>${esc(band(e)||'Yayın')}</span>`}<span class="radio-candidate-quality">${esc(q)}</span></div></button>`}
function why(e){const reasons=whyParts(e);if(!reasons.length)return'';return `<section class="radio-why"><div class="radio-section-title"><h3>Neden bu aday?</h3>${e?._radioConsole?`<button type="button" data-station-detail="${esc(e.schedule_id)}">Detaylı analiz →</button>`:''}</div><ul class="radio-reason-list">${reasons.map(x=>`<li><span>✓</span>${esc(x)}</li>`).join('')}</ul></section>`}
function emptyState(m){if(!guideReady())return '<div class="radio-empty" role="status"><b>Yayın rehberi hazırlanıyor</b><p>Veriler hazır olduğunda şu anda denenmeye değer yayınlar burada görünecek.</p></div>';const text=m==='ALL'?'Şu anda dinlemeye uygun bir yayın adayı yok.':`${m} bandında şu anda dinlemeye uygun bir yayın adayı yok.`;return `<div class="radio-empty" role="status">${esc(text)}</div>`}
async function refreshMw(force=false){if(!R.me?.id||!R.radioConsole?.loadMw)return[];if(!force&&mwLoadAttempted)return mwCandidates();mwLoadAttempted=true;mwLoadRequested=true;try{return await R.radioConsole.loadMw({limit:200,force})}catch(error){R.reportError?.(error,'now-mw-load',{silent:true});return[]}finally{mwLoadRequested=false}}
function render(){const root=ensure(),m=mode(),full=candidates(m),shown=full.slice(0,visibleLimit),lead=shown[0]||null,others=shown.slice(1,4),remaining=Math.max(0,full.length-shown.length);R.nowMode=m;root.innerHTML=`<section class="radio-console-screen"><div class="radio-console-head"><div class="radio-console-brand"><span class="radio-wave-logo" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i></span><div><h2>Radyo Günlüğüm</h2><p>Dünyayı dinle. Kayıt altına al.</p></div></div><span class="radio-location-chip">⌖ ${esc(originName())}</span></div><div class="radio-band-tabs" role="group" aria-label="Yayın bandı filtresi">${['ALL','MW','SW','FM'].map(x=>`<button type="button" class="${m===x?'active':''}" data-now-mode="${x}" aria-pressed="${m===x?'true':'false'}">${x==='ALL'?'Tümü':x}</button>`).join('')}</div><div class="radio-console-copy"><div><h2>Şu An ne dinlenir?</h2><p>${esc(labelNow())} · koşullara göre en iyi adaylar</p></div><button type="button" class="btn ghost radio-refresh" data-radio-refresh>↻ Yenile</button></div>${lead?featured(lead):mwLoadRequested?'<div class="radio-loading">MW adayları hazırlanıyor…</div>':emptyState(m)}${others.length?`<section class="radio-candidate-section"><div class="radio-section-title"><h3>Diğer dikkat çekici adaylar</h3><button type="button" data-route="guide">Tüm rehberi gör →</button></div><div class="radio-candidate-grid">${others.map(candidateCard).join('')}</div></section>`:''}${lead&&lead?._radioConsole?scale(lead.frequency):''}${lead?why(lead):''}${remaining?`<button type="button" class="btn ghost" data-now-more>${remaining.toLocaleString('tr-TR')} adayı daha göster</button>`:''}</section>`;if((m==='MW'||m==='ALL')&&R.me?.id&&R.radioConsole?.loadMw&&!mwCandidates().length&&!mwLoadRequested&&!mwLoadAttempted)refreshMw(false).then(()=>{if(R.router?.current?.()==='now')render()});return root}
function stopMinuteRefresh(){if(minuteTimer!==null){clearTimeout(minuteTimer);minuteTimer=null}}
function scheduleMinuteRefresh(){stopMinuteRefresh();if(R.router?.current?.()!=='now'||document.hidden)return;const delay=Math.max(250,60000-(Date.now()%60000)+75);minuteTimer=setTimeout(()=>{minuteTimer=null;if(R.router?.current?.()==='now'&&!document.hidden){if(mode()==='MW'||mode()==='ALL')refreshMw(true).finally(()=>render());else render();scheduleMinuteRefresh()}},delay)}
function scheduleRender(delay=0,{resetLimit=false}={}){if(resetLimit)visibleLimit=30;if(R.router?.current?.()!=='now')return;if(renderTimer!==null)clearTimeout(renderTimer);renderTimer=setTimeout(()=>{renderTimer=null;if(R.router?.current?.()==='now')render()},delay)}
function enter(){render();if(mode()==='MW'||mode()==='ALL')refreshMw(false).then(()=>scheduleRender());scheduleMinuteRefresh()}
document.addEventListener('click',e=>{if(!(e.target instanceof Element))return;const refresh=e.target.closest('[data-radio-refresh]');if(refresh){refresh.disabled=true;refreshMw(true).then(()=>render()).finally(()=>{if(refresh.isConnected)refresh.disabled=false});return}const more=e.target.closest('[data-now-more]');if(more){visibleLimit+=30;render();return}const b=e.target.closest('[data-now-mode]');if(!b)return;const v=b.dataset.nowMode;if(!MODES.has(v))return;visibleLimit=30;R.nowMode=v;if(R.uiState)R.uiState.nowMode=v;render();if(v==='MW'||v==='ALL')refreshMw(false).then(()=>scheduleRender())},true);
R.events?.on?.('store:updated',()=>scheduleRender());R.events?.on?.('guide:data-ready',()=>scheduleRender());R.events?.on?.('radio-console:mw-ready',()=>scheduleRender());R.events?.on?.('user:settings',()=>{mwLoadAttempted=false;scheduleRender(0,{resetLimit:true})});R.events?.on?.('auth:changed',()=>{mwLoadAttempted=false;scheduleRender(0,{resetLimit:true})});R.events?.on?.('route:changed',x=>{if(x?.to==='now')scheduleMinuteRefresh();else if(x?.from==='now')stopMinuteRefresh()});
document.addEventListener('visibilitychange',()=>{if(document.hidden)stopMinuteRefresh();else if(R.router?.current?.()==='now'){render();scheduleMinuteRefresh()}});
R.nowUI={render,ensure,mode,windowText,candidates,score,displayScore,quality,validCandidate,guideReady,emptyState,mwReasonChips,whyParts,scheduleMinuteRefresh,stopMinuteRefresh,refreshMw,get visibleLimit(){return visibleLimit}};R.router?.register?.('now',{prepare:ensure,enter});R.features?.register?.('now-ui',{ready:true,provider:'app-now-ui'});ensure();
})();