(()=>{
const R=window.R;if(!R||R.__memoryApp372)return;R.__memoryApp372=true;
const $=s=>document.querySelector(s),esc=v=>R.esc?R.esc(v):String(v??''),norm=v=>R.norm?R.norm(v):String(v??'').toLocaleLowerCase('tr-TR');
const KEY='radio-memory-v372';
const saved=(()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return{}}})();
const state={mode:['stations','frequencies','countries'].includes(saved.mode)?saved.mode:'stations',query:String(saved.query||''),filters:{band:saved.filters?.band||'',signal:saved.filters?.signal||'',status:saved.filters?.status||'',audio:!!saved.filters?.audio},profile:saved.profile?.kind&&saved.profile?.key?saved.profile:null};
let attempts=null,attemptsPromise=null;
function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch{}}
function loadCss(){if(document.querySelector('link[data-app-memory-css]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='app-memory.css';l.dataset.appMemoryCss='1';document.head.appendChild(l)}
function ensureView(){let tab=$('#tab-memory');if(!tab){tab=document.createElement('section');tab.id='tab-memory';tab.className='tab-view hidden';const app=$('#appView'),log=$('#tab-log');app?.insertBefore(tab,log||app.firstChild)}let root=$('#appMemory');if(!root){tab.replaceChildren();root=document.createElement('div');root.id='appMemory';root.className='app-memory';tab.appendChild(root)}return root}
function logs(){return Array.isArray(R.store?.state?.logs)?R.store.state.logs:(R.logs||[])}
function stationOf(x){return String(x?.station||x?.smart_station||'').trim()}
function split(v){return String(v||'').split(/[/,;]/).map(x=>x.trim()).filter(Boolean)}
function unitOf(x){return x?.band==='FM'?'MHz':'kHz'}
function freqKey(x){return x?.band&&x?.frequency!=null?`${x.band}|${Number(x.frequency).toFixed(3)}`:''}
function freqLabel(x){const n=Number(x?.frequency);return `${Number.isFinite(n)?n.toLocaleString('tr-TR',{maximumFractionDigits:3}):'—'} ${unitOf(x)}`}
function dateTime(x){return `${x?.date||''} ${String(x?.time||'').slice(0,5)}`.trim()}
function mapGroupsFromStore(kind){const idx=R.store?.index;if(!idx)return null;if(kind==='station')return [...idx.stations.entries()].map(([key,items])=>({kind,key,label:stationOf(items[0])||key,logs:items}));if(kind==='country')return [...idx.countries.entries()].map(([key,items])=>({kind,key,label:split(items[0]?.country).find(c=>norm(c)===key)||key,logs:[...new Map(items.map(x=>[x.id,x])).values()]}));if(kind==='frequency')return [...idx.frequencies.entries()].map(([key,items])=>({kind,key,label:freqLabel(items[0]),band:items[0]?.band,frequency:Number(items[0]?.frequency),logs:items}));return null}
function groupSubset(kind,source){const m=new Map();for(const x of source){if(kind==='station'){const label=stationOf(x),key=norm(label);if(!key)continue;if(!m.has(key))m.set(key,{kind,key,label,logs:[]});m.get(key).logs.push(x)}else if(kind==='country'){for(const label of split(x.country)){const key=norm(label);if(!key)continue;if(!m.has(key))m.set(key,{kind,key,label,logs:[]});if(!m.get(key).logs.some(z=>z.id===x.id))m.get(key).logs.push(x)}}else if(kind==='frequency'){const key=freqKey(x);if(!key)continue;if(!m.has(key))m.set(key,{kind,key,label:freqLabel(x),band:x.band,frequency:Number(x.frequency),logs:[]});m.get(key).logs.push(x)}}return [...m.values()]}
function sortedGroups(kind,source=null){let a;if(source)a=groupSubset(kind,source);else a=mapGroupsFromStore(kind)||groupSubset(kind,logs());return a.sort((x,y)=>y.logs.length-x.logs.length||x.label.localeCompare(y.label,'tr'))}
function candidateLogs(){let source=logs();const q=norm(state.query.trim()),min=Number(state.filters.signal||0);if(q&&R.store?.search){const ids=new Set(R.store.search(state.query,500).filter(x=>x.kind==='log').map(x=>x.id));source=source.filter(x=>ids.has(x.id)||norm([stationOf(x),x.country,x.language,x.program,x.notes,x.transcript,x.band,x.frequency].join(' ')).includes(q))}return source.filter(x=>{if(state.filters.band&&x.band!==state.filters.band)return false;if(min&&Number(x.signal_strength||0)<min)return false;if(state.filters.status&&x.status!==state.filters.status)return false;if(state.filters.audio&&!x.audio_path)return false;if(!q)return true;return norm([stationOf(x),x.country,x.language,x.program,x.notes,x.transcript,x.band,x.frequency,x.smart_station,x.smart_program].join(' ')).includes(q)})}
function signals(a){return a.map(x=>Number(x.signal_strength)).filter(Number.isFinite)}
function avg(a){const s=signals(a);return s.length?(s.reduce((p,n)=>p+n,0)/s.length).toFixed(1):'—'}
function maxSig(a){const s=signals(a);return s.length?Math.max(...s):'—'}
function unique(a,fn){return [...new Set(a.flatMap(x=>{const v=fn(x);return Array.isArray(v)?v:[v]}).map(v=>String(v||'').trim()).filter(Boolean))]}
function firstLast(a){const s=[...a].sort((x,y)=>dateTime(x).localeCompare(dateTime(y)));return{first:s[0]?.date||'—',last:s.at(-1)?.date||'—'}}
function bestHour(a){const m=new Map();for(const x of a){const h=Number(String(x.time||'').slice(0,2));if(Number.isFinite(h))m.set(h,(m.get(h)||0)+1)}if(!m.size)return'—';const h=[...m.entries()].sort((a,b)=>b[1]-a[1]||a[0]-b[0])[0][0];return `${String(h).padStart(2,'0')}:00–${String((h+1)%24).padStart(2,'0')}:00`}
function count(a,fn){const m=new Map();for(const x of a){for(const v of [].concat(fn(x)||[])){const s=String(v||'').trim();if(s)m.set(s,(m.get(s)||0)+1)}}return [...m.entries()].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0],'tr'))}
function bars(items){if(!items.length)return'<div class="am-empty">Veri yok.</div>';const mx=Math.max(...items.map(x=>x[1]),1);return items.slice(0,8).map(([k,v])=>`<div class="am-bar"><span>${esc(k)}</span><i><b style="width:${Math.round(v/mx*100)}%"></b></i><strong>${v}</strong></div>`).join('')}
function card(g){const fl=firstLast(g.logs);let meta='';if(g.kind==='station')meta=`${unique(g.logs,x=>x.frequency!=null?freqLabel(x):'').length} frekans · son ${fl.last}`;if(g.kind==='frequency')meta=`${esc(g.band)} · ${unique(g.logs,stationOf).length} istasyon · son ${fl.last}`;if(g.kind==='country')meta=`${unique(g.logs,stationOf).length} istasyon · ${unique(g.logs,x=>split(x.language)).length} dil`;return `<button class="am-card" data-am-profile="${g.kind}" data-am-key="${encodeURIComponent(g.key)}"><span>${g.kind==='station'?'İstasyon':g.kind==='frequency'?'Frekans':'Ülke'}</span><h4>${esc(g.label)}</h4><p>${meta}</p><div><b>${g.logs.length} kayıt</b><b>Ort. ${avg(g.logs)}/5</b></div></button>`}
function overview(){return{logs:logs(),stations:sortedGroups('station'),frequencies:sortedGroups('frequency'),countries:sortedGroups('country')}}
function renderBrowse(){const root=ensureView(),o=overview(),filtered=candidateLogs(),kind=state.mode==='stations'?'station':state.mode==='frequencies'?'frequency':'country',groups=sortedGroups(kind,filtered),title=state.mode==='stations'?'İstasyonlar':state.mode==='frequencies'?'Frekanslar':'Ülkeler';root.innerHTML=`<section class="am-hero"><span>KİŞİSEL RADYO HAFIZASI</span><h2>Radyo Hafızası</h2><p>Kayıtların istasyon, frekans ve ülke profillerine otomatik dönüşür.</p><div class="am-search"><input id="amSearch" value="${esc(state.query)}" placeholder="İstasyon, frekans, ülke, dil veya not…"><button class="btn ghost" id="amClear" type="button">Temizle</button></div></section><div class="am-summary"><div><b>${o.stations.length}</b><span>istasyon</span></div><div><b>${o.frequencies.length}</b><span>frekans</span></div><div><b>${o.countries.length}</b><span>ülke</span></div><div><b>${o.logs.length}</b><span>kayıt</span></div></div><section class="am-section"><div class="am-head"><div><h3>${title}</h3><p>${filtered.length} kayıt üzerinden</p></div></div><div class="am-tabs">${[['stations','İstasyonlar'],['frequencies','Frekanslar'],['countries','Ülkeler']].map(([k,l])=>`<button class="${state.mode===k?'active':''}" data-am-mode="${k}">${l}</button>`).join('')}</div><details class="am-filters" ${state.filters.band||state.filters.signal||state.filters.status||state.filters.audio?'open':''}><summary>Gelişmiş filtreler</summary><div><select id="amBand"><option value="">Tüm bantlar</option>${(R.B||[]).map(b=>`<option value="${esc(b)}" ${state.filters.band===b?'selected':''}>${esc(b)}</option>`).join('')}</select><select id="amSignal"><option value="">Tüm sinyaller</option>${[2,3,4,5].map(n=>`<option value="${n}" ${String(state.filters.signal)===String(n)?'selected':''}>${n}/5 ve üzeri</option>`).join('')}</select><select id="amStatus"><option value="">Tüm durumlar</option><option value="confirmed" ${state.filters.status==='confirmed'?'selected':''}>Doğrulandı</option><option value="candidate" ${state.filters.status==='candidate'?'selected':''}>Aday</option></select><label><input id="amAudio" type="checkbox" ${state.filters.audio?'checked':''}> Sesli kayıt</label></div></details><div class="am-grid">${groups.length?groups.slice(0,120).map(card).join(''):'<div class="am-empty">Bu arama ve filtrelerle eşleşen profil yok.</div>'}</div></section>`;bindBrowse()}
function bindBrowse(){const search=$('#amSearch');if(search)search.addEventListener('input',()=>{state.query=search.value;save();clearTimeout(R.__amTimer);R.__amTimer=setTimeout(renderBrowse,160)});$('#amClear')?.addEventListener('click',()=>{state.query='';state.filters={band:'',signal:'',status:'',audio:false};save();renderBrowse()});document.querySelectorAll('[data-am-mode]').forEach(b=>b.addEventListener('click',()=>{state.mode=b.dataset.amMode;state.profile=null;save();renderBrowse()}));for(const [id,k] of [['amBand','band'],['amSignal','signal'],['amStatus','status']])$('#'+id)?.addEventListener('change',e=>{state.filters[k]=e.target.value;save();renderBrowse()});$('#amAudio')?.addEventListener('change',e=>{state.filters.audio=e.target.checked;save();renderBrowse()});document.querySelectorAll('[data-am-profile]').forEach(b=>b.addEventListener('click',()=>openProfile(b.dataset.amProfile,decodeURIComponent(b.dataset.amKey))))}
function findGroup(kind,key){return sortedGroups(kind).find(x=>x.key===key)||null}
async function loadAttempts(){if(attempts)return attempts;if(attemptsPromise)return attemptsPromise;if(!R.me)return[];attemptsPromise=(async()=>{const q=await R.S.from('radio_session_attempts').select('band,frequency,result,signal_strength,attempted_at').eq('user_id',R.me.id).order('attempted_at',{ascending:false}).limit(2000);if(q.error){R.reportError?.(q.error,'memory-attempts',{silent:true});return[]}attempts=q.data||[];return attempts})().finally(()=>attemptsPromise=null);return attemptsPromise}
function attemptStats(g){if(g.kind!=='frequency'||!attempts)return null;const tol=g.band==='FM'?.01:1,a=attempts.filter(x=>x.band===g.band&&Math.abs(Number(x.frequency)-Number(g.frequency))<=tol);if(!a.length)return null;return{total:a.length,heard:a.filter(x=>x.result==='heard').length,weak:a.filter(x=>x.result==='weak').length,none:a.filter(x=>x.result==='none').length}}
function logRow(x){return `<article class="am-log"><div><b>${esc(stationOf(x)||freqLabel(x))}</b><span>${esc(x.date)} · ${esc(String(x.time||'').slice(0,5))}</span></div><p>${esc([x.band,x.frequency!=null?freqLabel(x):'',x.language,x.country,x.program].filter(Boolean).join(' · '))}</p><div>${x.signal_strength?`<span>${x.signal_strength}/5</span>`:''}${x.status==='confirmed'?'<span>Doğrulandı</span>':''}${x.audio_path?'<span>Ses</span>':''}${x.qsl_status==='received'?'<span>QSL</span>':''}<button type="button" data-am-log="${x.id}">Kaydı aç</button></div></article>`}
async function renderProfile(kind,key){const root=ensureView(),g=findGroup(kind,key);if(!g){state.profile=null;save();return renderBrowse()}state.profile={kind,key};save();if(kind==='frequency'&&!attempts)await loadAttempts();const a=g.logs,fl=firstLast(a),att=attemptStats(g),left=kind==='station'?count(a,x=>x.frequency!=null?[freqLabel(x)]:[]):count(a,stationOf),right=count(a,x=>split(x.language)),confirmed=a.filter(x=>x.status==='confirmed').length,audio=a.filter(x=>x.audio_path).length,qsl=a.filter(x=>x.qsl_status==='received').length,sub=kind==='station'?`${unique(a,x=>split(x.country)).join(', ')||'Ülke belirsiz'} · ${unique(a,x=>x.band).join(', ')}`:kind==='frequency'?`${g.band} · ${g.label}`:`${unique(a,stationOf).length} istasyon · ${unique(a,x=>x.band).join(', ')}`;root.innerHTML=`<section class="am-profile"><button class="am-back" type="button" data-am-back>← Radyo Hafızası</button><span>${kind==='station'?'İSTASYON':kind==='frequency'?'FREKANS':'ÜLKE'} PROFİLİ</span><h2>${esc(g.label)}</h2><p>${esc(sub)}</p><div class="am-primary-metrics"><div><b>${a.length}</b><span>kayıt</span></div><div><b>${avg(a)}/5</b><span>ortalama</span></div><div><b>${maxSig(a)}/5</b><span>en güçlü</span></div><div><b>${bestHour(a)}</b><span>en iyi saat</span></div></div></section><section class="am-section"><details class="am-more"><summary>Daha fazla istatistik</summary><div class="am-more-grid"><div><b>${confirmed}</b><span>doğrulandı</span></div><div><b>${fl.first}</b><span>ilk kayıt</span></div><div><b>${fl.last}</b><span>son kayıt</span></div><div><b>${audio}</b><span>ses örneği</span></div><div><b>${qsl}</b><span>QSL cevabı</span></div>${att?`<div><b>${att.heard+att.weak}/${att.total}</b><span>denemede alındı</span></div>`:''}</div></details></section>${att?`<section class="am-section"><div class="am-head"><div><h3>Dinleme denemeleri</h3><p>Başarılı ve başarısız denemeler dahil</p></div></div><div class="am-summary"><div><b>${att.heard}</b><span>yakalandı</span></div><div><b>${att.weak}</b><span>zayıf</span></div><div><b>${att.none}</b><span>yok</span></div><div><b>${att.total}</b><span>toplam</span></div></div></section>`:''}<section class="am-section"><div class="am-two"><div><h3>${kind==='station'?'Frekanslar':'İstasyonlar'}</h3>${bars(left)}</div><div><h3>Diller</h3>${bars(right)}</div></div></section><section class="am-section"><div class="am-head"><div><h3>Kayıt geçmişi</h3><p>${a.length} dinleme kaydı</p></div></div><div class="am-logs">${[...a].sort((x,y)=>dateTime(y).localeCompare(dateTime(x))).map(logRow).join('')}</div></section>`;bindProfile()}
function bindProfile(){$('[data-am-back]')?.addEventListener('click',()=>{state.profile=null;save();renderBrowse()});document.querySelectorAll('[data-am-log]').forEach(b=>b.addEventListener('click',()=>{const id=b.dataset.amLog;R.edit?.(id);R.router?.go?.('log',{source:'memory-log'})||R.switch?.('log')}))}
function openProfile(kind,key){renderProfile(kind,key)}
function render(){loadCss();ensureView();if(state.profile)return renderProfile(state.profile.kind,state.profile.key);return renderBrowse()}
function injectMenu(){const sheet=$('#v38Sheet');if(!sheet||sheet.querySelector('[data-app-memory-menu]'))return;const groups=[...sheet.querySelectorAll('.v38-menu-group')],collection=groups.find(x=>norm(x.querySelector('summary')?.textContent).includes('koleksiyon')),list=collection?.querySelector('.v38-menu-list');if(!list)return;const b=document.createElement('button');b.type='button';b.className='v38-menu-row';b.dataset.appMemoryMenu='1';b.innerHTML='<span style="display:block;color:inherit;font-size:inherit"><b>Radyo Hafızası</b><small>İstasyon, frekans ve ülke profilleri</small></span><span>›</span>';b.addEventListener('click',()=>{document.querySelector('#v38Overlay')?.remove();document.querySelector('#v38Sheet')?.remove();R.router?.go?.('memory',{source:'menu'})||R.switch?.('memory')});list.prepend(b)}
document.addEventListener('click',e=>{if(e.target.closest('[data-v38menu]'))setTimeout(injectMenu,0)},true);
R.openRadioMemory=(kind,key)=>{state.profile=kind&&key?{kind,key}:null;save();ensureView();R.router?.go?.('memory',{source:'search'})||R.switch?.('memory');setTimeout(render,0)};
R.memory={state,render,index:()=>({stations:sortedGroups('station'),frequencies:sortedGroups('frequency'),countries:sortedGroups('country')})};
R.router?.register?.('memory',{enter:()=>render()});
R.events?.on?.('store:updated',()=>{attempts=null;if(R.router?.current?.()==='memory')render()});
R.features?.register?.('memory',{ready:true,provider:'app-memory'});
loadCss();ensureView();if(R.uiState?.tab==='memory'||R.router?.current?.()==='memory')setTimeout(render,0);
})();
