const R=window.R={};
R.__coreBase=true;
R.URL='https://mesbtntnclokgzgunept.supabase.co';
R.KEY='sb_publishable_sUZxv1oXvj8y3oOKhXGNtw_BwoiREML';
R.S=supabase.createClient(R.URL,R.KEY);
R.$=s=>document.querySelector(s);
R.$$=s=>[...document.querySelectorAll(s)];
R.B=['FM','MW','SW1','SW2','SW3','SW4','SW5','SW6','SW7','SW8','SW9','SW10'];
R.me=null;
R.logs=[];
R.schedules=[];
R.guideEntries=[];
R.guideRules=[];
R.bandProfiles=[];
R.nowMode='ALL';
R.lastSmart=null;
R.editAudio=null;
R.recordedBlob=null;
R.esc=(v='')=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
R.norm=(s='')=>String(s).toLocaleLowerCase('tr-TR').normalize('NFD').replace(/[\u0300-\u036f]/g,'');
R.num=v=>v===''||v==null?null:Number(v);
R.today=()=>new Date().toLocaleDateString('en-CA');
R.local=()=>{const d=new Date(),x=new Date(d-d.getTimezoneOffset()*60000).toISOString();return{date:x.slice(0,10),time:x.slice(11,16),month:x.slice(0,7)}};
R.freq=x=>`${Number(x?.frequency).toLocaleString('tr-TR',{maximumFractionDigits:3})} ${x?.band==='FM'?'MHz':'kHz'}`;
R.download=(name,text,type='text/plain;charset=utf-8')=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
R.fill=(id,value='')=>{const el=R.$('#'+id);if(el)el.value=value??''};
