(()=>{
const R=window.R,$=R.$;
R.count=(a,f)=>{const m=new Map();a.forEach(x=>{const k=f(x)||'Belirsiz';m.set(k,(m.get(k)||0)+1)});return[...m.entries()].sort((a,b)=>b[1]-a[1])};
R.bars=(e,a)=>{if(!e)return;const m=Math.max(1,...a.map(x=>x[1]));e.innerHTML=a.length?a.slice(0,12).map(([k,v])=>`<div class=bar-row><span>${R.esc(k)}</span><div class=bar-track><div class=bar-fill style="width:${v/m*100}%"></div></div><b>${v}</b></div>`).join(''):'<p class=hint>Henüz veri yok.</p>'};
R.renderAnalysis=()=>{const s=R.logs.filter(x=>x.signal_strength),avg=s.length?(s.reduce((a,x)=>a+Number(x.signal_strength),0)/s.length).toFixed(1):'—',i=[['Ortalama sinyal',avg],['Ses örneği',R.logs.filter(x=>x.audio_path).length],['QSL gönderildi',R.logs.filter(x=>['sent','received'].includes(x.qsl_status)).length],['Konum',new Set(R.logs.map(x=>x.location).filter(Boolean)).size]];if($('#analysisCards'))$('#analysisCards').innerHTML=i.map(([k,v])=>`<div class=stat><b>${v}</b><small>${k}</small></div>`).join('');R.bars($('#bandBars'),R.count(R.logs,x=>x.band));R.bars($('#langBars'),R.count(R.logs,x=>x.language));R.bars($('#stationBars'),R.count(R.logs.filter(x=>x.station),x=>x.station));const g=new Map();s.forEach(x=>{const h=Number(String(x.time).slice(0,2)),k=`${x.band}|${h}`,z=g.get(k)||{band:x.band,hour:h,sum:0,n:0};z.sum+=Number(x.signal_strength);z.n++;g.set(k,z)});const p=[...g.values()].map(x=>({...x,avg:x.sum/x.n})).sort((a,b)=>b.avg-a.avg||b.n-a.n).slice(0,6);if($('#predictions'))$('#predictions').innerHTML=p.length?p.map(x=>`<div class=prediction><b>${x.band} • ${String(x.hour).padStart(2,'0')}:00–${String((x.hour+1)%24).padStart(2,'0')}:00</b><br>Ortalama sinyal ${x.avg.toFixed(1)}/5 • ${x.n} kayıt</div>`).join(''):'<p class=hint>Sinyal puanlı kayıtlar biriktikçe kişisel tahmin burada oluşacak.</p>'};
R.map=null;R.layer=null;R.renderMap=()=>{const p=R.logs.filter(x=>x.latitude!=null&&x.longitude!=null);if($('#mapCount'))$('#mapCount').textContent=`${p.length} konumlu kayıt`;if(!$('#map')||typeof L==='undefined')return;if(!R.map){R.map=L.map('map').setView([38.151,27.36],9);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(R.map);R.layer=L.layerGroup().addTo(R.map)}R.map.invalidateSize();R.layer.clearLayers();p.forEach(x=>L.marker([Number(x.latitude),Number(x.longitude)]).bindPopup(`<b>${R.esc(x.station||'Radyo kaydı')}</b><br>${R.esc(x.date)} ${R.esc(String(x.time).slice(0,5))}<br>${R.esc(R.freq(x))}<br>${R.esc(x.location||'')}`).addTo(R.layer));if(p.length)R.map.fitBounds(L.latLngBounds(p.map(x=>[Number(x.latitude),Number(x.longitude)])).pad(.2),{maxZoom:13})};
if($('#calendarMonth'))$('#calendarMonth').onchange=()=>R.renderCalendar();R.renderCalendar=()=>{if(!$('#calendarGrid'))return;const v=$('#calendarMonth').value||R.local().month,[y,m]=v.split('-').map(Number),f=new Date(y,m-1,1),days=new Date(y,m,0).getDate(),st=(f.getDay()+6)%7,n=['Pzt','Sal','Çar','Per','Cum','Cmt','Paz'],c=new Map();R.logs.forEach(x=>{if(x.date?.startsWith(v)){const d=Number(x.date.slice(8,10));c.set(d,(c.get(d)||0)+1)}});let h=n.map(x=>`<div class=cal-head>${x}</div>`).join('');for(let i=0;i<st;i++)h+='<div class="cal-day out"></div>';for(let d=1;d<=days;d++){const q=c.get(d)||0;h+=`<div class=cal-day data-calday="${v}-${String(d).padStart(2,'0')}"><span class=num>${d}</span>${q?`<span class=cal-count>${q} kayıt</span>`:''}</div>`}$('#calendarGrid').innerHTML=h};if($('#calendarGrid'))$('#calendarGrid').onclick=e=>{const d=e.target.closest('[data-calday]');if(!d)return;$('#filterDate').value=d.dataset.calday;R.switch('log');R.renderRecords()};
function utcStamp(x){const t=String(x.time||'00:00').slice(0,5),d=new Date(`${x.date}T${t}:00+03:00`);if(Number.isNaN(d.getTime()))return{date:x.date,time:t};return{date:d.toISOString().slice(0,10),time:d.toISOString().slice(11,16)}}
R.qsl=x=>{const u=utcStamp(x);return`Reception Report / QSL Request\n\nStation: ${x.station||x.smart_station||'Unknown'}\nDate (Türkiye): ${x.date}\nTime (Türkiye, UTC+3): ${String(x.time).slice(0,5)}\nDate / Time (UTC): ${u.date} ${u.time} UTC\nFrequency: ${R.freq(x)}\nReception location: ${x.location||'Bozköy, Torbalı, İzmir'}\nLanguage: ${x.language||''}\nProgramme / details heard: ${x.program||x.transcript||''}\nSignal report (personal 1–5 scale): ${x.signal_strength||'N/A'} / 5\nReceiver: Tecsun R-9012\n\nI would be grateful if you could confirm this reception report with a QSL / e-QSL.\nThank you.`};
R.renderQsl=()=>{if(!$('#qslList'))return;const a=R.logs.filter(x=>x.qsl_status!=='none'||x.station||x.smart_station);$('#qslList').innerHTML=a.length?a.map(x=>`<div class=qsl-item data-qslitem=${x.id}><div class=record-top><div><b>${R.esc(x.station||x.smart_station||'İsimsiz')}</b><div class=small>${R.esc(x.date)} • ${R.esc(R.freq(x))}</div></div><span class="badge ${x.qsl_status==='received'?'ok':x.qsl_status==='sent'?'gold':''}">${({none:'Başlatılmadı',planned:'Gönderilecek',sent:'Gönderildi',received:'Cevap geldi'})[x.qsl_status]||'Başlatılmadı'}</span></div><div class=row-actions><button class="btn ghost" data-copyqsl=${x.id}>Raporu kopyala</button><button class="btn ghost" data-planned=${x.id}>Planla</button><button class="btn ghost" data-sent=${x.id}>Gönderildi</button><button class="btn ghost" data-received=${x.id}>Cevap geldi</button></div><details><summary>Rapor metni</summary><div class=qsl-report>${R.esc(R.qsl(x))}</div></details></div>`).join(''):'<p class=hint>Henüz kayıt yok.</p>'};if($('#qslList'))$('#qslList').onclick=async e=>{for(const a of ['copyqsl','planned','sent','received']){const b=e.target.closest(`[data-${a}]`);if(!b)continue;const x=R.logs.find(z=>z.id===b.dataset[a]);if(!x)return;if(a==='copyqsl'){try{await navigator.clipboard.writeText(R.qsl(x));b.textContent='Kopyalandı'}catch{alert(R.qsl(x))}return}const p=a==='planned'?{qsl_status:'planned'}:a==='sent'?{qsl_status:'sent',qsl_sent_at:R.today()}:{qsl_status:'received',qsl_received_at:R.today()},z=await R.S.from('radio_logs').update(p).eq('id',x.id).eq('user_id',R.me.id);if(z.error)alert(z.error.message);else await R.load();return}};
for(const id of ['guideBand','guideFreq'])if($('#'+id))$('#'+id).addEventListener('input',()=>R.renderGuide());if($('#guideSearch'))$('#guideSearch').oninput=()=>R.renderGuide();
R.renderGuide=()=>{if(!$('#guideList'))return;const b=$('#guideBand')?.value||'',f=Number($('#guideFreq')?.value),q=R.norm($('#guideSearch')?.value||''),source=(R.guideEntries||[]).filter(x=>x.entry_type==='station_target');const a=source.filter(x=>{const band=x.mode==='SW'?x.band:x.mode,tol=x.mode==='FM'?.3:x.mode==='MW'?12:25;return(!b||band===b)&&(!f||Math.abs(Number(x.frequency)-f)<=tol)&&(!q||R.norm([x.station,x.language_content,x.country,x.content_hint,x.time_text].join(' ')).includes(q))}).sort((x,y)=>String(x.mode).localeCompare(String(y.mode))||Number(x.frequency)-Number(y.frequency));$('#guideList').innerHTML=a.length?a.slice(0,150).map(x=>{const band=x.mode==='SW'?x.band:x.mode,unit=x.unit||(x.mode==='FM'?'MHz':'kHz');return`<div class=guide-item><div class=record-top><div><strong>${R.esc(x.station||'Aday yayın')}</strong><div class=small>${R.esc(band)} • ${Number(x.frequency).toLocaleString('tr-TR')} ${R.esc(unit)}${x.time_text?` • ${R.esc(x.time_text)}`:''}</div></div><span class=badge>${R.esc((x.language_content||'').split(/[;/]/)[0]||'')}</span></div><p>${R.esc(x.country||'')} — ${R.esc(x.content_hint||x.language_content||'')}</p><div class=small>Kaynak: ${R.esc(x.source_doc||'Rehber')} ${x.valid_to?'• geçerlilik: '+R.esc(x.valid_to):''}</div><button class="btn ghost" data-guideapply=${x.id}>Yeni kayda uygula</button></div>`}).join(''):'<p class=hint>Eşleşen yayın yok.</p>'};
if($('#guideList'))$('#guideList').onclick=e=>{const b=e.target.closest('[data-guideapply]');if(!b)return;const x=(R.guideEntries||[]).find(z=>z.id===b.dataset.guideapply);if(!x)return;if(R.prefillGuide)return R.prefillGuide(x);R.reset();R.fill('band',x.mode==='SW'?x.band:x.mode);R.fill('frequency',x.frequency);R.fill('station',x.station);R.fill('language',(x.language_content||'').split(/[;/]/)[0]);R.fill('country',x.country);R.fill('program',x.content_hint);R.unit();R.switch('log')};

const modules=['v24-achievements.js','v25-smart-listening.js','v26-radio-atlas.js','v30-ai-radio-assistant.js','v33-stability-hotfix.js','v34-current-programs.js','v35-audit-fixes.js'];
function loadModule(src){if(document.querySelector(`script[src="${src}"],script[src="./${src}"]`))return Promise.resolve();return new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=()=>reject(new Error(`${src} yüklenemedi`));document.head.appendChild(s)})}
(async()=>{for(const src of modules)await loadModule(src);if(!R.__booted){R.__booted=true;await R.boot()}})().catch(e=>{console.error(e);if($('#authMsg'))$('#authMsg').textContent='Uygulama başlatılamadı: '+e.message});
})();
