importScripts('./app-config.js');
const CFG=globalThis.RADIO_APP_CONFIG||{cacheVersion:'v385-core-boundary-20260907-1'};
const CACHE=`radyo-${CFG.cacheVersion}`;
const RADIO_INTELLIGENCE_POLISH='20260916-5';
const STATION_DETAIL_ACCESSIBILITY='20260916-6';
const FAVORITES_DISCOVERY='20260916-7';
const PERSONAL_FAVORITE_SCORING='20260916-8';
const FAVORITE_EVENT_SCOPES='20260916-9';
const CURRENT_FAVORITES_SCOPE='20260916-10';
const MW_GUIDE_MATCH_INDEX='20260916-11';
const MW_GUIDE_RENDER_SNAPSHOT='20260916-12';
const MW_REAL_TONIGHT_PLANNER='20260916-13';
const RADIO_SURFACE_HARMONY='20260916-14';
const RADIO_SURFACE_WAVE2='20260916-15';
const RADIO_SURFACE_OVERLAYS='20260916-16';
const NOW_RENDER_SNAPSHOT='20260916-17';
const STATION_DETAIL_HISTORY_INDEX='20260916-18';
const UI_INTEGRITY_PASS='20260916-19';
const DESIGN_TOKEN_FOUNDATION='20260916-20';
const DESIGN_TOKEN_PHASE2A='20260916-21';
const DESIGN_TOKEN_PHASE2B='20260916-22';
const DESIGN_TOKEN_PHASE2C='20260916-23';
const DESIGN_TOKEN_PHASE2D='20260916-24';
const DESIGN_TOKEN_PHASE2E='20260916-25';
const DESIGN_TOKEN_PHASE2F='20260916-26';
const DESIGN_TOKEN_PHASE2G='20260916-27';
const LOCAL=['./','./index.html','./app-config.js','./styles.css','./app-base.css','./core.js','./app-bootstrap.js','./app-ui-mode.js','./v38-ux-cleanup.css','./v41-propagation-assistant.css','./app-space-weather.css','./v42-design-system.css','./app-visual-polish.css','./app-deep-audit.css','./app-audit-polish.css','./app-desktop.css','./app-ui-integrity.css','./app-design-tokens.css','./app-page-density.css','./app-page-density-night.css','./app-radio-surface-theme.css','./app-radio-surface-extended.css','./app-radio-surface-overlays.css','./v44-search-rebuild.css','./v44-search-rebuild.js','./app-foundation.css','./app-foundation.js','./app-toast.css','./app-toast.js','./app-pwa-install.js','./app-runtime-core.js','./app-auth-service.js','./app-router-core.js','./app-auth-ui.js','./app-broadcast-locale.js','./app-station-intelligence.js','./app-station-streams.js','./app-current-programs.js','./app-guide-service.js','./app-guide.css','./app-guide-ui.js','./app-mw-guide.css','./app-mw-guide-ui.js','./app-language-service.js','./app-qsl-service.js','./app-record-service.js','./app-record-integrity.js','./app-offline-service.js','./app-smart-analyzer.js','./app-ai-service.js','./app-ai.css','./app-ai-ui.js','./app-achievements-service.js','./app-user-services.js','./app-listening-service.js','./app-atlas-service.js','./app-radio-intelligence.js','./app-radio-console-service.js','./app-radio-console.css','./app-radio-console-polish.css','./app-favorites-ui.css','./app-favorites-ui.js','./app-radio-intelligence.css','./app-radio-intelligence-ui.js','./app-shell-core.js','./app-collection.css','./app-collection-ui.js','./app-menu.css','./app-menu-ui.js','./app-quick-log.css','./app-quick-log.js','./app-home-ui.js','./app-now-ui.js','./app-station-detail-ui.js','./app-log-ui.js','./app-log-form.css','./app-log-form-ui.js','./app-audio-ui.js','./app-analysis-ui.js','./app-map-ui.js','./app-calendar-ui.js','./app-qsl-ui.js','./app-listening.css','./app-listening-ui.js','./app-modal-accessibility.js','./app-atlas.css','./app-atlas-ui.js','./app-propagation.js','./app-space-weather.js','./app-memory.css','./app-memory.js','./app-page-density.js','./app-radio-glossary.css','./app-radio-glossary.js','./app-radio-tooltips.js','./app-audio-safety.js','./app-backup.js','./app-pwa-updates.css','./app-pwa-updates.js','./app-ui-state.js','./app-smoke.js','./manifest.webmanifest','./icon.svg'];
const CRITICAL=['./','./index.html','./app-config.js','./core.js','./app-bootstrap.js','./app-ui-mode.js','./app-foundation.js','./app-runtime-core.js','./app-auth-service.js','./app-router-core.js','./app-ui-state.js','./app-auth-ui.js'];
const EXTERNAL=['https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.116.0','https://unpkg.com/leaflet@1.9.4/dist/leaflet.js','https://unpkg.com/leaflet@1.9.4/dist/leaflet.css'];
const REQUIRED_LOCAL=new Set(LOCAL.filter(u=>u.endsWith('.js')&&!CRITICAL.includes(u))),REQUIRED_EXTERNAL=new Set([EXTERNAL[0]]);
const EXTERNAL_SET=new Set(EXTERNAL),LOCAL_SET=new Set(LOCAL.map(u=>new URL(u,self.location.href).href));
async function cacheOne(cache,url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(`${url}: HTTP ${r.status}`);await cache.put(url,r.clone())}
self.addEventListener('install',event=>{event.waitUntil((async()=>{const c=await caches.open(CACHE),results=await Promise.allSettled(LOCAL.map(u=>cacheOne(c,u))),failed=results.flatMap((r,i)=>r.status==='rejected'?[LOCAL[i]]:[]),criticalFailed=failed.filter(u=>CRITICAL.includes(u));if(criticalFailed.length){await caches.delete(CACHE);throw new Error(`PWA çekirdek dosyaları önbelleğe alınamadı: ${criticalFailed.join(', ')}`)}const requiredLocalFailed=failed.filter(u=>REQUIRED_LOCAL.has(u));if(requiredLocalFailed.length){await caches.delete(CACHE);throw new Error(`PWA uygulama modülleri önbelleğe alınamadı: ${requiredLocalFailed.join(', ')}`)}if(failed.length)console.warn('Bazı isteğe bağlı PWA varlıkları önbelleğe alınamadı:',failed);const externalResults=await Promise.allSettled(EXTERNAL.map(u=>cacheOne(c,u))),externalFailed=externalResults.flatMap((r,i)=>r.status==='rejected'?[EXTERNAL[i]]:[]),requiredExternalFailed=externalFailed.filter(u=>REQUIRED_EXTERNAL.has(u));if(requiredExternalFailed.length){await caches.delete(CACHE);throw new Error(`PWA zorunlu dış bağımlılığı önbelleğe alınamadı: ${requiredExternalFailed.join(', ')}`)}if(externalFailed.length)console.warn('Bazı isteğe bağlı dış PWA varlıkları önbelleğe alınamadı:',externalFailed)})())});
self.addEventListener('message',event=>{if(event.data?.type==='SKIP_WAITING')self.skipWaiting()});
self.addEventListener('activate',event=>{event.waitUntil((async()=>{for(const k of await caches.keys())if(k.startsWith('radyo-')&&k!==CACHE)await caches.delete(k);await self.clients.claim()})())});
self.addEventListener('fetch',event=>{const req=event.request;if(req.method!=='GET')return;const url=new URL(req.url),sameOrigin=url.origin===self.location.origin,allowedExternal=EXTERNAL_SET.has(url.href),knownLocal=LOCAL_SET.has(url.href);if(!sameOrigin&&!allowedExternal)return;if(url.hostname.endsWith('supabase.co')||url.hostname.endsWith('swpc.noaa.gov'))return;if(req.mode==='navigate'){event.respondWith((async()=>{const c=await caches.open(CACHE),cached=await c.match('./index.html');try{const r=await fetch(req,{cache:'no-store'});if(r&&r.ok){await c.put('./index.html',r.clone());return r}return cached||r||Response.error()}catch{return cached||Response.error()}})());return}if(sameOrigin&&!knownLocal)return;event.respondWith((async()=>{const c=await caches.open(CACHE),cached=await c.match(req),network=fetch(req).then(async r=>{if(r&&r.ok)await c.put(req,r.clone());return r}).catch(()=>null);return cached||await network||Response.error()})())});