(()=>{
const R=window.R;if(!R)return;const $=R.$;
R.guideEntries=[];R.guideRules=[];R.bandProfiles=[];R.nowMode='ALL';R.scanQueue=[];R.scanIndex=0;
const css=`
.v21-hero{background:linear-gradient(135deg,#293529,#465343);color:#fff;border-radius:15px;padding:18px;margin-bottom:12px}.v21-hero h2{font-size:25px;margin:0 0 4px}.v21-clock{font:700 27px Georgia,serif}.v21-modebar{display:flex;gap:6px;flex-wrap:wrap;margin:12px 0}.v21-mode{border:1px solid var(--line);background:#fff;border-radius:999px;padding:7px 12px;font-weight:800;cursor:pointer}.v21-mode.active{background:var(--accent);color:#fff;border-color:var(--accent)}.v21-grid{display:grid;grid-template-columns:1.25fr .75fr;gap:12px}.now-card{border:1px solid var(--line);border-radius:12px;background:#fff;padding:12px;margin:8px 0}.now-rank{font:800 12px system-ui;color:var(--muted)}.now-frequency{font:700 22px Georgia,serif}.candidate-score{display:inline-block;background:#e8eadf;color:#34402f;padding:4px 8px;border-radius:999px;font-weight:800}.candidate-score.hot{background:#d9ead4}.why{font-size:12px;color:var(--muted);margin-top:6px}.rulebox{background:#f5f0df;border:1px solid #ded3b8;border-radius:11px;padding:12px;margin:8px 0}.bandchips{display:flex;gap:6px;flex-wrap:wrap}.bandchip{padding:6px 9px;border-radius:8px;background:#efeee7;border:1px solid var(--line);font-weight:800}.bandchip.best{background:#dce8d7}.bandchip.bad{opacity:.55}.identify-grid{display:grid;grid-template-columns:.8fr .8fr 1fr 1fr;gap:8px}.identify-result{margin-top:10px}.scanbox{border:2px solid #a37d38;border-radius:14px;padding:15px;background:#fffaf0}.scan-big{font:700 29px Georgia,serif}.expiry{padding:8px 10px;border-radius:9px;background:#f5f0df;margin-top:8px}.expiry.warn{background:#f4dfd9;color:#70362e}.source-note{font-size:11px;color:var(--muted);margin-top:10px}@media(max-width:850px){.v21-grid{grid-template-columns:1fr}.identify-grid{grid-template-columns:1fr 1fr}}@media(max-width:520px){.identify-grid{grid-template-columns:1fr}.v21-clock{font-size:23px}}
`;
const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);
const tab=document.createElement('button');tab.className='main-tab';tab.dataset.tab='now';tab.textContent='📡 Şu An';const nav=document.querySelector('.main-tabs');nav?.insertBefore(tab,nav.firstChild);
const view=document.createElement('section');view.id='tab-now';view.className='tab-view hidden';view.innerHTML=`
<div class="v21-hero"><div class="eyebrow" style="color:#d9dfd3">V2.1 • AKILLI REHBER</div><h2>Şu an ne dinleyebilirim?</h2><div id="v21Clock" class="v21-clock"></div><div id="v21Location">Bozköy, Torbalı, İzmir • Türkiye saati</div><div id="v21Expiry" class="expiry"></div></div>
<div class="v21-modebar"><button class="v21-mode active" data-vmode="ALL">Tümü</button><button class="v21-mode" data-vmode="SW">Kısa dalga</button><button class="v21-mode" data-vmode="MW">Orta dalga</button><button class="v21-mode" data-vmode="FM">FM</button></div>
<div class="v21-grid">
<section class="card"><div class="section-head"><div><h2>Şu anda denenebilecekler</h2><p class="hint">Saat, rehber olasılığı, SW bant koşulu ve kendi geçmiş kayıtların birlikte puanlanır.</p></div><button id="v21Refresh" class="btn ghost">Yenile</button></div><div id="v21Rules"></div><div id="v21Suggestions"></div></section>
<section class="card"><h2>Önce hangi SW bandı?</h2><p class="hint">Rehberdeki saat-bant yoğunluk tablosu.</p><div id="v21Bands" class="bandchips"></div><hr><h2>Canlı tarama</h2><p class="hint">Önerileri sırayla radyoda dene.</p><button id="scanStart" class="btn primary">🧭 Taramayı başlat</button><div id="scanBox" class="hidden"></div></section>
</div>
<section class="card" style="margin-top:12px"><h2>🔎 Bu yayın ne olabilir?</h2><p class="hint">Analog kadran sapmasını hesaba katarak frekans + saat + dil/metin ile adayları karşılaştırır.</p><div class="identify-grid"><select id="idMode"><option value="SW">SW</option><option value="MW">MW</option><option value="FM">FM</option></select><select id="idBand"><option value="SW1">SW1</option><option value="SW2">SW2</option><option value="SW3">SW3</option><option value="SW4">SW4</option><option value="SW5">SW5</option><option value="SW6">SW6</option><option value="SW7">SW7</option><option value="SW8">SW8</option><option value="SW9">SW9</option><option value="SW10">SW10</option></select><input id="idFreq" type="number" step="0.001" placeholder="Frekans (SW/MW kHz, FM MHz)"><input id="idLang" placeholder="Dil veya duyulan kelimeler"></div><div style="margin-top:8px"><button id="identifyBtn" class="btn primary">Adayları bul</button></div><div id="identifyResult" class="identify-result"></div></section>`;
const app=document.querySelector('#appView');const log=document.querySelector('#tab-log');app?.insertBefore(view,log);
tab.onclick=()=>R.switch('now');
const oldSwitch=R.switch;R.switch=t=>{oldSwitch(t);if(t==='now')R.renderV21?.()};
const oldLoad=R.load;R.load=async()=>{await oldLoad();const [a,b,c]=await Promise.all([R.S.from('guide_entries').select('*').eq('entry_type','station_target'),R.S.from('guide_time_rules').select('*'),R.S.from('guide_band_profiles').select('*')]);if(a.error)throw a.error;if(b.error)throw b.error;if(c.error)throw c.error;R.guideEntries=a.data||[];R.guideRules=b.data||[];R.bandProfiles=c.data||[];R.renderV21?.()};
const mins=()=>{const d=new Date();return d.getHours()*60+d.getMinutes()},today=()=>new Date().toLocaleDateString('en-CA'),inRange=(m,r)=>{let[a,b]=r||[];if(a==null||b==null)return false;if(b===1440)return m>=a;if(a===b)return true;return a<b?m>=a&&m<b:m>=a||m<b},active=e=>!e.time_ranges?.length||e.time_ranges.some(r=>inRange(mins(),r));
const validity=e=>{const d=today();return(!e.valid_from||d>=e.valid_from)&&(!e.valid_to||d<=e.valid_to)};
const profileFor=band=>R.bandProfiles.find(p=>p.band===band&&inRange(mins(),[p.start_minute,p.end_minute]));const profAdj={'Çok iyi':15,'İyi':8,'Orta':0,'Zayıf':-12,'Boş':-25,'Genelde boş':-25};
const history=e=>{const tol=e.mode==='FM'?.25:e.mode==='MW'?12:30,a=R.logs.filter(x=>(e.mode==='SW'?String(x.band).startsWith('SW'):x.band===e.band)&&Math.abs(Number(x.frequency)-Number(e.frequency))<=tol&&x.signal_strength);if(!a.length)return{adj:0,text:''};const av=a.reduce((s,x)=>s+Number(x.signal_strength),0)/a.length;return{adj:Math.round((av-2.5)*5),text:`Geçmişin: ${a.length} deneme, ort. ${av.toFixed(1)}/5`}};
R.scoreEntry=e=>{let score=Number(e.probability_score||50),why=[];if(e.time_ranges?.length){if(active(e)){score+=22;why.push('saat eşleşiyor')}else{score-=30;why.push('yayın saati dışında')}}else if(e.mode==='FM'){score+=5;why.push('FM frekansı gün boyu aday')}if(e.mode==='SW'){const p=profileFor(e.band);if(p){score+=profAdj[p.rating]||0;why.push(`${e.band}: ${p.rating}`)}}const h=history(e);score+=h.adj;if(h.text)why.push(h.text);if(!validity(e)){score-=50;why.push('çizelge geçerlilik dışında')}return{score:Math.max(1,Math.min(99,Math.round(score))),why}};
R.currentSuggestions=()=>R.guideEntries.filter(e=>R.nowMode==='ALL'||e.mode===R.nowMode).map(e=>({...e,_s:R.scoreEntry(e)})).filter(e=>e._s.score>=20).sort((a,b)=>b._s.score-a._s.score||Number(a.frequency)-Number(b.frequency));
const formatFreq=e=>`${Number(e.frequency).toLocaleString('tr-TR',{maximumFractionDigits:3})} ${e.unit}`;
const card=(e,i)=>`<article class="now-card"><div class="record-top"><div><div class="now-rank">#${i+1} • ${R.esc(e.mode)} ${e.band!==e.mode?'• '+R.esc(e.band):''}</div><div class="now-frequency">${formatFreq(e)}</div><div class="record-title">${R.esc(e.station||'Aday frekans')}</div></div><span class="candidate-score ${e._s.score>=80?'hot':''}">${e._s.score}/99 aday puanı</span></div><p>${R.esc(e.language_content||e.content_hint||'')}</p><div class="badges">${e.time_text?`<span class=badge>🕒 ${R.esc(e.time_text)}</span>`:''}${e.dial_position?`<span class=badge>🎚️ ${R.esc(e.dial_position)}</span>`:''}${e.direction?`<span class=badge>🧭 ${R.esc(e.direction)}</span>`:''}</div>${e.action_hint?`<div class=why>${R.esc(e.action_hint)}</div>`:''}<div class=why>${R.esc(e._s.why.join(' • '))}</div><button class="btn ghost" data-vprefill="${e.id}">Kayda uygula</button></article>`;
R.renderV21=()=>{const d=new Date();$('#v21Clock').textContent=d.toLocaleString('tr-TR',{weekday:'long',hour:'2-digit',minute:'2-digit',day:'2-digit',month:'long'});const end=new Date('2026-10-24T23:59:59'),diff=Math.ceil((end-d)/(864e5));const ex=$('#v21Expiry');if(diff>=0){ex.className='expiry';ex.textContent=`A26 kısa dalga çizelgesi: ${diff} gün daha geçerli. 25 Ekim sonrası B26 güncellemesi gerekir.`}else{ex.className='expiry warn';ex.textContent='A26 kısa dalga çizelgesinin süresi doldu. SW önerilerini B26 ile güncellemek gerekir.'}const rules=R.guideRules.filter(r=>(R.nowMode==='ALL'||r.mode===R.nowMode)&&r.time_ranges?.some(x=>inRange(mins(),x)));$('#v21Rules').innerHTML=rules.map(r=>`<div class=rulebox><b>${R.esc(r.mode)} • ${R.esc(r.label||r.time_text)}</b><div>${R.esc(r.expected_content||'')}</div>${r.band_hint?`<div class=small>Öncelik: ${R.esc(r.band_hint)}</div>`:''}${r.frequencies_text?`<div class=small>Hedefler: ${R.esc(r.frequencies_text)}</div>`:''}${r.action_hint?`<div class=small>${R.esc(r.action_hint)}</div>`:''}</div>`).join('')||'<p class=hint>Bu mod için saat kuralı yok.</p>';const ps=R.bandProfiles.filter(p=>inRange(mins(),[p.start_minute,p.end_minute])).sort((a,b)=>(profAdj[b.rating]||0)-(profAdj[a.rating]||0));$('#v21Bands').innerHTML=ps.map(p=>`<span class="bandchip ${(profAdj[p.rating]||0)>=8?'best':(profAdj[p.rating]||0)<0?'bad':''}">${p.band} • ${p.rating}</span>`).join('');const a=R.currentSuggestions().slice(0,12);$('#v21Suggestions').innerHTML=a.length?a.map(card).join(''):'<p class=hint>Bu filtrede uygun aday bulunamadı.</p>'};
view.addEventListener('click',e=>{const p=e.target.closest('[data-vprefill]');if(p){const x=R.guideEntries.find(z=>z.id===p.dataset.vprefill);if(x)R.prefillGuide(x,3)} });
R.prefillGuide=(x,sig)=>{R.reset();R.fill('band',x.mode==='FM'?'FM':x.mode==='MW'?'MW':x.band);R.fill('frequency',x.frequency);R.fill('station',x.station);R.fill('country',x.country);R.fill('program',x.content_hint);if(x.language_content)R.fill('language',x.language_content.split(/[;/]/)[0]);if(sig)R.fill('signal',sig);if(x.direction)R.fill('antennaDirection',x.direction);if(x.dial_position)R.fill('dialPosition',x.dial_position);R.unit();R.switch('log')};
document.querySelectorAll('.v21-mode').forEach(b=>b.onclick=()=>{document.querySelectorAll('.v21-mode').forEach(x=>x.classList.remove('active'));b.classList.add('active');R.nowMode=b.dataset.vmode;R.renderV21()});$('#v21Refresh').onclick=()=>R.renderV21();
$('#idMode').onchange=()=>{$('#idBand').disabled=$('#idMode').value!=='SW'};
$('#identifyBtn').onclick=()=>{const mode=$('#idMode').value,band=mode==='SW'?$('#idBand').value:mode,f=Number($('#idFreq').value),txt=R.norm($('#idLang').value);if(!f)return $('#identifyResult').innerHTML='<p class=msg>Frekans gir.</p>';const tol=mode==='FM'?.35:mode==='MW'?18:35;let a=R.guideEntries.filter(e=>e.mode===mode&&(mode!=='SW'||e.band===band)&&Math.abs(Number(e.frequency)-f)<=tol).map(e=>{let z=R.scoreEntry(e).score,why=[];const dist=Math.abs(Number(e.frequency)-f);z+=Math.round(25*(1-dist/tol));why.push(`frekans farkı ${dist.toLocaleString('tr-TR',{maximumFractionDigits:2})} ${e.unit}`);if(txt&&R.norm([e.language_content,e.station,e.country,e.content_hint].join(' ')).includes(txt)){z+=18;why.push('dil/metin eşleşmesi')}return{...e,_s:{score:Math.min(99,z),why:[...R.scoreEntry(e).why,...why]}}}).sort((a,b)=>b._s.score-a._s.score).slice(0,5);$('#identifyResult').innerHTML=a.length?a.map(card).join(''):'<p class=hint>Bu frekans çevresinde rehber adayı bulunamadı. Analog kadran için biraz daha geniş aralık deneyebilirsin.</p>'};
$('#scanStart').onclick=()=>{R.scanQueue=R.currentSuggestions().filter((x,i,a)=>a.findIndex(y=>y.mode===x.mode&&y.frequency===x.frequency&&y.station===x.station)===i).slice(0,20);R.scanIndex=0;R.renderScan()};R.renderScan=()=>{const box=$('#scanBox');if(!R.scanQueue.length||R.scanIndex>=R.scanQueue.length){box.classList.remove('hidden');box.innerHTML='<div class=scanbox><b>Tarama tamamlandı.</b><p class=hint>Yeni saate göre önerileri yenileyebilirsin.</p></div>';return}const x=R.scanQueue[R.scanIndex];box.classList.remove('hidden');box.innerHTML=`<div class=scanbox><div class=small>${R.scanIndex+1}/${R.scanQueue.length} • ${x.mode} ${x.band}</div><div class=scan-big>${formatFreq(x)}</div><h3>${R.esc(x.station||'Aday')}</h3><p>${R.esc(x.language_content||x.content_hint||'')}</p>${x.dial_position?`<p>🎚️ ${R.esc(x.dial_position)}</p>`:''}${x.direction?`<p>🧭 ${R.esc(x.direction)}</p>`:''}<span class=candidate-score>${x._s.score}/99</span><div class=row-actions style="margin-top:12px"><button class="btn primary" data-scan="heard">Duyuyorum</button><button class="btn ghost" data-scan="weak">Zayıf</button><button class="btn ghost" data-scan="none">Yok</button><button class="btn ghost" data-scan="next">Sonraki</button></div></div>`};$('#scanBox').onclick=e=>{const b=e.target.closest('[data-scan]');if(!b)return;const x=R.scanQueue[R.scanIndex];if(b.dataset.scan==='heard')return R.prefillGuide(x,3);if(b.dataset.scan==='weak')return R.prefillGuide(x,2);R.scanIndex++;R.renderScan()};
setInterval(()=>{if(!view.classList.contains('hidden'))R.renderV21()},60000);
})();